### ISSUE TITLE
Relational Filter - minus joins

### ISSUE THREAD

**Issue by vmendiratta** [sirensolutions/kibi#11]
Firstly, great work you guys on siren join and kibi!

Is there a way for me to do minus/not joins on Kibi? The relational filter (using siren-join) constructs a left join elastic search query. Can the relational filter be configured to construct a minus join query?

Suppose, I've 2 indices - emails sent and users and I wish to find users who haven't been sent an email.

I was able to do this using a plain elastic search query (as an external REST datasource) and including the results on the dashboard using a template. This seemed a little cumbersome and unintuitive.

Is there any plan to provide this feature on the relational filter itself?

Thanks.

**Comment by jccq** [comment]
Hi Vijay

yes there is support, just create a normal filter (E.g. with the
"relational button" ) and then click  the "-" button on the filter (as in
regular kibana) ..  it will change color, see below.  these are just the
articles from companies that are NOT in the west of US :)

[image: Inline image 1]

On Tue, Feb 9, 2016 at 7:35 AM, Vijay Mendiratta notifications@github.com
wrote:

> Firstly, great work you guys on siren join and kibi!
> 
> Is there a way for me to do minus/not joins on Kibi? The relational filter
> (using siren-join) constructs a left join elastic search query. Can the
> relational filter be configured to construct a minus join query?
> 
> Suppose, I've 2 indices - emails sent and users and I wish to find users
> who haven't been sent an email.
> 
> I was able to do this using a plain elastic search query (as an external
> REST datasource) and including the results on the dashboard using a
> template. This seemed a little cumbersome and unintuitive.
> 
> Is there any plan to provide this feature on the relational filter itself?
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sirensolutions/kibi/issues/11.

## 

Giovanni Tummarello
CEO - SIREn Solutions

**Comment by vmendiratta** [comment]
Thanks Giovanni.

I can't see the image you've uploaded.

But for my use case, I'd like:
Companies which don't find a mention in any article

Can this be done using a regular kibana feature - inverting a filter?

**Comment by jccq** [comment]
Sorry for the attachement, didnt work over email response

.. but yes just create the relational filter from articles to companies and
then invert it . Should work like a charm also at multiple nested (negated)
levels, let me know if you have issues.

Note also that for external queries (those made on REST or SQL) you can do
the same.. this is done in the aggregator configurator (typically in the
VISUALIZE menu when you do a widget using our "external query" aggregator)
in there you'll find a "negate the results" checkbox.

In the demo we distribute the "external ring" of the "pie chart" in the
"investment" dashboard is configured with one such SQL query in plain and
in NOT mode

enjoy :)

**Comment by scampi** [comment]
@vmendiratta Could you prepare a small test data using the 2 indices from your example (users and emails) ? I will try to list the steps needed to achieve what you want.

**Comment by vmendiratta** [comment]
[github-kibi-issue.txt](https://github.com/sirensolutions/kibi/files/122857/github-kibi-issue.txt)

Hi Stephane, please find some sample test data attached.

Thanks.

**Comment by jccq** [comment]
did it not work from the UI as i described? :)

On Tue, Feb 9, 2016 at 10:01 AM, Vijay Mendiratta notifications@github.com
wrote:

> github-kibi-issue.txt
> https://github.com/sirensolutions/kibi/files/122857/github-kibi-issue.txt
> 
> Hi Stephane, please find some sample test data attached.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sirensolutions/kibi/issues/11#issuecomment-181792194.

## 

Giovanni Tummarello
CEO - SIREn Solutions

**Comment by vmendiratta** [comment]
Hi Giovanni

Something is breaking somewhere. I'm not able to put a finger on what yet.

In reality, my data is split across 3 indices - emails opened, emails sent and users.

Emails opened and emails sent have a common field - campaign name.
Emails sent and users have a common field - email.
Emails opened and users have a common field - email.

My task is to find out users that received a particular type (campaign) of email but did not open it.

I'm having trouble figuring out which filter to invert.

I apologize for having described the problem so naively the first time.

**Comment by jccq** [comment]
Hi Vijay, the filter should work technically, but please do write me at
giovanni@siren.solutions and we'll be able to support specifically if you
wish - that is our business model :)

looking forward to support

On Tue, Feb 9, 2016 at 11:51 AM, Vijay Mendiratta notifications@github.com
wrote:

> Hi Giovanni
> 
> Something is breaking somewhere. I'm not able to put a finger on what yet.
> 
> In reality, my data is split across 3 indices - emails opened, emails sent
> and users.
> 
> Emails opened and emails sent have a common field - campaign name.
> Emails sent and users have a common field - email.
> Emails opened and users have a common field - email.
> 
> My task is to find out users that received a particular type (campaign) of
> email but did not open it.
> 
> I'm having trouble figuring out which filter to invert.
> 
> I apologize for having described the problem so naively the first time.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sirensolutions/kibi/issues/11#issuecomment-181831894.

## 

Giovanni Tummarello
CEO - SIREn Solutions

**Comment by vmendiratta** [comment]
Thanks for all the help Giovanni :) I appreciate!
Will spend some more time with this.

**Comment by scampi** [comment]
@vmendiratta please re-open if you have some issue.
