### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by tslarkin61** [sirensolutions/kibi#12]
I get the following error when I start kibi after installing the software:

``` json
{
  "name": "Kibana",
  "hostname": "ip-172-31-31-231",
  "pid": 7814,
  "level": 50,
  "err": {
    "message": {
      "root_cause": [
        {
          "type": "search_parse_exception",
          "reason": "No mapping found for [buildNum] in order to sort on"
        }
      ],
      "type": "search_phase_execution_exception",
      "reason": "all shards failed",
      "phase": "query",
      "grouped": true,
      "failed_shards": [
        {
          "shard": 0,
          "index": ".kibi",
          "node": "kfiuoBvdTLaE3oHD-0d2pw",
          "reason": {
            "type": "search_parse_exception",
            "reason": "No mapping found for [buildNum] in order to sort on"
          }
        }
      ]
    },
    "name": "Error",
    "stack": "Error: [object Object]\n at respond (/opt/kibi-0.2.0-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:235:15)\n at checkRespForFailure (/opt/kibi-0.2.0-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:203:7)\n at HttpConnector. (/opt/kibi-0.2.0-linux-x64/src/node_modules/elasticsearch/src/lib/connectors/http.js:156:7)\n at IncomingMessage.bound (/opt/kibi-0.2.0-linux-x64/src/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)\n at IncomingMessage.emit (events.js:117:20)\n at _stream_readable.js:944:16\n at process._tickCallback (node.js:442:13)"
  },
  "msg": "",
  "time": "2016-02-10T20:57:07.598Z",
  "v": 0
}
```

Any assistance would be appreciated.

**Comment by scampi** [comment]
Are you trying the demo shipped with kibi, or is this on your data ?
Can you describe the steps you did to cause this error ?

Is `buildNum` a field of the index you want to query ?

**Comment by scampi** [comment]
A shot in the dark: what is the output of the command below ?

``` sh
$ curl 'http://localhost:9220/.kibi/_search' -d '{ "query": { "term": { "_type": "config" } } }'
```

**Comment by tslarkin61** [comment]
This error occurs when I execute the command ./bin/kibi to start the server
the very first time after downloading and configuring the elasticsearch URL.

The error actually occurs in the elasticsearch process. The kibi process
stops immediately.

Here is my current list of indices:

[ec2-user@ip-172-31-24-242 ~]$ curl 'localhost:9200/_cat/indices?v'
health status index               pri rep docs.count docs.deleted
store.size pri.store.size
yellow open   webpagetest           5   1        827            0
 443.7kb        443.7kb
yellow open   .kibi                 5   1          3            0
16.5kb         16.5kb
yellow open   .kibana               1   1         10            0
18.9kb         18.9kb
yellow open   bank                  5   1       1000            0
 449.2kb        449.2kb
yellow open   logstash-2016.01.26   5   1        103            0
 254.5kb        254.5kb
yellow open   customer              5   1          2            0
 7.5kb          7.5kb
yellow open   shakespeare           5   1     111396            0
17.7mb         17.7mb

The majority of these are samples which come directly from elasticsearch
documentation. The webpagetest index is mine built and populated with my
ETL software.
I would imagine the state of any given index should not stop kibi from
starting properly.

On Wed, Feb 10, 2016 at 5:38 PM, Stéphane Campinas <notifications@github.com

**Comment by tslarkin61** [comment]
Here is the result:

[ec2-user@ip-172-31-24-242 ~]$ curl 'localhost:9200/.kibi/search' -d '

> { "query" : { "term" : { "_type" : "config" } } } ';
> {"_index":".kibi","_type":"search","_id":"AVLQZsNbNw6C6k7NMM7K","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"created":true}

Does that tell you anything?

On Thu, Feb 11, 2016 at 7:10 AM, Stéphane Campinas <notifications@github.com

**Comment by scampi** [comment]
Hmmm could you provide me the following:
- version of kibi
- version of elasticsearch
- `config/kibi.yml`

You forgot the `_` before `search`. You should have something similar to what is below:

``` json
{
  "took": 48,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": ".kibi",
        "_type": "config",
        "_id": "4.4.0",
        "_score": 1,
        "_source": {
          "buildNum": 8467,
          "defaultIndex": "company",
          "kibi:timePrecision": "h"
        }
      }
    ]
  }
}
```

Now in relation with the error reported, it might seem you have an incomplete index. Maybe the package is corrupt ?

**Comment by tslarkin61** [comment]
Kibi version is 0.2.0
ElasticSearch version is 2.2.0
Here is the query you requested:
[ec2-user@ip-172-31-24-242 ~]$ curl 'localhost:9200/.kibi/_search?pretty'
-d '
{ "query" : { "term" : { "_type" : "config" } } } ';
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
Here is the kibi,yml file:

# Kibi configuration file.

# Kibi is served by a back end server. This controls which port to use.

port: 5602

# The host to bind the server to.

host: "localhost"

# The Elasticsearch instance to use for all your queries.

elasticsearch_url: "http://52.27.121.137:9200"

# If set to true, the server will send the hostname specified in

`elasticsearch_url`.

# If set to false, the server will send the hostname

elasticsearch_preserve_host: true

# Kibi uses an index in Elasticsearch to store saved searches,

visualizations

# and dashboards. It will create a new index if it doesn't already exist.

kibana_index: ".kibi"

# If your Elasticsearch is protected with basic auth, this is the user

credentials

# used by the the server to perform maintenance on the index at statup. Your

# users will still need to authenticate with Elasticsearch (which is

proxied by

# the server)

# kibana_elasticsearch_username: user

# kibana_elasticsearch_password: pass

# If your Elasticsearch requires client certificate and key

# kibana_elasticsearch_client_crt: /path/to/your/client.crt

# kibana_elasticsearch_client_key: /path/to/your/client.key

# The path to the CA certificate PEM file.

# ca: /path/to/your/CA.pem

# The default application to load.

default_app_id: "dashboard"

# Time in milliseconds to wait for elasticsearch to respond to pings,

defaults to

# request_timeout setting

# ping_timeout: 1500

# Time in milliseconds to wait for responses from the back end or

elasticsearch.

# This must be > 0

request_timeout: 300000

# Time in milliseconds for Elasticsearch to wait for responses from shards.

# Set to 0 to disable.

shard_timeout: 0

# Time in milliseconds to wait for Elasticsearch at startup before retrying

# startup_timeout: 5000

# Set to false to skip certificate validation

verify_ssl: true

# If you need to provide a CA certificate for your Elasticsearch instance,

put

# the path of the pem file here.

# ca: /path/to/your/CA.pem

# SSL for outgoing requests from the Kibi Server (PEM formatted)

# ssl_key_file: /path/to/your/server.key

# ssl_cert_file: /path/to/your/server.crt

# Set the path to where you would like the process id file to be created.

# pid_file: /var/run/kibi.pid

# If you would like to send the log output to a file you can set the path

below.

# This will also turn off the STDOUT log output.

log_file: ./kibi.log

# log_level: DEBUG

# A value to use as a XSRF token. This token is sent back to the server on

each request

# and required if you want to execute requests from other clients (like

curl).

# xsrf_token: ""

# Set to true to enable datasource query cache

datasource_enable_cache: true

# The datasource query cache size

datasource_cache_size: 500

# The max age of an object in the cache, in milliseconds

datasource_cache_max_age: 3600000

# The encryption algorithm used to encrypt sensitive datasource

configuration

# fields.

#

# Valid values:

# AES-GCM

datasource_encryption_algorithm: 'AES-GCM'

#The encryption key in base64 format; to change the key, use the

# bin/replace_encryption_key script

datasource_encryption_key: 'iSxvZRYisyUW33FreTBSyJJ34KpEquWznUPDvn+ka14='

# The default dashboard to load. Works only when default_app_id='dashboard'

default_dashboard_id: Articles

# load jdbc java bindings

load_jdbc: false

# Plugins that are included in the build, and no longer found in the

plugins/ folder
bundled_plugin_ids:
- plugins/dashboard/index
- plugins/discover/index
- plugins/doc/index
- plugins/kibana/index
- plugins/kibi/index
- plugins/kibi_default/index
- plugins/markdown_vis/index
- plugins/metric_vis/index
- plugins/settings/index
- plugins/sindicetech/index
- plugins/table_vis/index
- plugins/vis_types/index
- plugins/visualize/index

On Thu, Feb 11, 2016 at 9:31 AM, Stéphane Campinas <notifications@github.com

**Comment by jccq** [comment]
Kibi 0.2 only supports ES 1.X
please use a ES 1.X (With the Siren Join plugin installed) or wait for Kibi
0.3, which will be out any day now (might want to sign up to the release
mailing list, on the website)  thanks for trying

I think the new Kibi based on Kibana 4.4 should give a more graceful clear
message if the ES backend is not the one expected - we'll check if that's
the case to avoid future problems.

On Thu, Feb 11, 2016 at 3:25 PM, Timothy Larkin notifications@github.com
wrote:

> Kibi version is 0.2.0
> ElasticSearch version is 2.2.0
> Here is the query you requested:
> [ec2-user@ip-172-31-24-242 ~]$ curl 'localhost:9200/.kibi/_search?pretty'
> -d '
> { "query" : { "term" : { "_type" : "config" } } } ';
> {
> "took" : 2,
> "timed_out" : false,
> "_shards" : {
> "total" : 5,
> "successful" : 5,
> "failed" : 0
> },
> "hits" : {
> "total" : 0,
> "max_score" : null,
> "hits" : [ ]
> }
> }
> Here is the kibi,yml file:
> 
> # Kibi configuration file.
> 
> # Kibi is served by a back end server. This controls which port to use.
> 
> port: 5602
> 
> # The host to bind the server to.
> 
> host: "localhost"
> 
> # The Elasticsearch instance to use for all your queries.
> 
> elasticsearch_url: "http://52.27.121.137:9200"
> 
> # If set to true, the server will send the hostname specified in
> 
> `elasticsearch_url`.
> 
> # If set to false, the server will send the hostname
> 
> elasticsearch_preserve_host: true
> 
> # Kibi uses an index in Elasticsearch to store saved searches,
> 
> visualizations
> 
> # and dashboards. It will create a new index if it doesn't already exist.
> 
> kibana_index: ".kibi"
> 
> # If your Elasticsearch is protected with basic auth, this is the user
> 
> credentials
> 
> # used by the the server to perform maintenance on the index at statup.
> 
> Your
> 
> # users will still need to authenticate with Elasticsearch (which is
> 
> proxied by
> 
> # the server)
> 
> # kibana_elasticsearch_username: user
> 
> # kibana_elasticsearch_password: pass
> 
> # If your Elasticsearch requires client certificate and key
> 
> # kibana_elasticsearch_client_crt: /path/to/your/client.crt
> 
> # kibana_elasticsearch_client_key: /path/to/your/client.key
> 
> # The path to the CA certificate PEM file.
> 
> # ca: /path/to/your/CA.pem
> 
> # The default application to load.
> 
> default_app_id: "dashboard"
> 
> # Time in milliseconds to wait for elasticsearch to respond to pings,
> 
> defaults to
> 
> # request_timeout setting
> 
> # ping_timeout: 1500
> 
> # Time in milliseconds to wait for responses from the back end or
> 
> elasticsearch.
> 
> # This must be > 0
> 
> request_timeout: 300000
> 
> # Time in milliseconds for Elasticsearch to wait for responses from shards.
> 
> # Set to 0 to disable.
> 
> shard_timeout: 0
> 
> # Time in milliseconds to wait for Elasticsearch at startup before retrying
> 
> # startup_timeout: 5000
> 
> # Set to false to skip certificate validation
> 
> verify_ssl: true
> 
> # If you need to provide a CA certificate for your Elasticsearch instance,
> 
> put
> 
> # the path of the pem file here.
> 
> # ca: /path/to/your/CA.pem
> 
> # SSL for outgoing requests from the Kibi Server (PEM formatted)
> 
> # ssl_key_file: /path/to/your/server.key
> 
> # ssl_cert_file: /path/to/your/server.crt
> 
> # Set the path to where you would like the process id file to be created.
> 
> # pid_file: /var/run/kibi.pid
> 
> # If you would like to send the log output to a file you can set the path
> 
> below.
> 
> # This will also turn off the STDOUT log output.
> 
> log_file: ./kibi.log
> 
> # log_level: DEBUG
> 
> # A value to use as a XSRF token. This token is sent back to the server on
> 
> each request
> 
> # and required if you want to execute requests from other clients (like
> 
> curl).
> 
> # xsrf_token: ""
> 
> # Set to true to enable datasource query cache
> 
> datasource_enable_cache: true
> 
> # The datasource query cache size
> 
> datasource_cache_size: 500
> 
> # The max age of an object in the cache, in milliseconds
> 
> datasource_cache_max_age: 3600000
> 
> # The encryption algorithm used to encrypt sensitive datasource
> 
> configuration
> 
> # fields.
> 
> #
> 
> # Valid values:
> 
> # AES-GCM
> 
> datasource_encryption_algorithm: 'AES-GCM'
> 
> #The encryption key in base64 format; to change the key, use the
> 
> # bin/replace_encryption_key script
> 
> datasource_encryption_key: 'iSxvZRYisyUW33FreTBSyJJ34KpEquWznUPDvn+ka14='
> 
> # The default dashboard to load. Works only when default_app_id='dashboard'
> 
> default_dashboard_id: Articles
> 
> # load jdbc java bindings
> 
> load_jdbc: false
> 
> # Plugins that are included in the build, and no longer found in the
> 
> plugins/ folder
> bundled_plugin_ids:
> - plugins/dashboard/index
> - plugins/discover/index
> - plugins/doc/index
> - plugins/kibana/index
> - plugins/kibi/index
> - plugins/kibi_default/index
> - plugins/markdown_vis/index
> - plugins/metric_vis/index
> - plugins/settings/index
> - plugins/sindicetech/index
> - plugins/table_vis/index
> - plugins/vis_types/index
> - plugins/visualize/index
> 
> On Thu, Feb 11, 2016 at 9:31 AM, Stéphane Campinas <
> notifications@github.com
> 
> > wrote:
> > 
> > Hmmm could you provide me the following:
> > - version of kibi
> > - version of elasticsearch
> > - config/kibi.yml
> > 
> > You forgot the _ before search. You should have something similar to what
> > is below:
> > 
> > {
> > "took": 48,
> > "timed_out": false,
> > "_shards": {
> > "total": 5,
> > "successful": 5,
> > "failed": 0
> > },
> > "hits": {
> > "total": 1,
> > "max_score": 1,
> > "hits": [
> > {
> > "_index": ".kibi",
> > "_type": "config",
> > "_id": "4.4.0",
> > "_score": 1,
> > "_source": {
> > "buildNum": 8467,
> > "defaultIndex": "company",
> > "kibi:timePrecision": "h"
> > }
> > }
> > ]
> > }
> > }
> > 
> > Now in relation with the error reported, it might seem you have an
> > incomplete index. Maybe the package is corrupt ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sirensolutions/kibi/issues/12#issuecomment-182888887
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sirensolutions/kibi/issues/12#issuecomment-182915079.

## 

Giovanni Tummarello
CEO - SIREn Solutions

**Comment by scampi** [comment]
@tslarkin61 ES 1.7.x is fine
