### ISSUE TITLE
sparql over http datasource

### ISSUE THREAD

**Issue by zorino** [sirensolutions/kibi#14]
Can't make a query work over a sparql http datasource.

Keeps getting "Parameter 'url' must be a string, not undefined" in the the json preview.

**Comment by szydan** [comment]
Thanks for reporting this 
The fixed will be published in 0.3.1 release.

**Comment by michimau** [comment]
is it fixed? :)

**Comment by jccq** [comment]
well some sort of 0.3.1 is out - can you give it a try?

On Mon, Mar 7, 2016 at 2:26 PM, michimau notifications@github.com wrote:

> is it fixed? :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sirensolutions/kibi/issues/14#issuecomment-193270490.

## 

Giovanni Tummarello
CEO - SIREn Solutions

**Comment by michimau** [comment]
it does work against "semantic.eea.europa.eu/sparql"
well done!

**Comment by jccq** [comment]
:)! thanks

On Mon, Mar 7, 2016 at 3:13 PM, michimau notifications@github.com wrote:

> it does work against "semantic.eea.europa.eu/sparql"
> well done!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sirensolutions/kibi/issues/14#issuecomment-193292099.

## 

Giovanni Tummarello
CEO - SIREn Solutions
