### ISSUE TITLE
Marvel sense plugin not compatible with 0.3.1

### ISSUE THREAD

**Issue by NTBTI** [sirensolutions/kibi#16]
Grabbed the latest full demo (0.3.1) and installed. Installed the absolutely most crucial plugin Marvel/Sense and got this when restarting Kibi:

[error][status][plugin:marvel] Status changed from yellow to red - Marvel version 2.2.0 is not supported with Kibana 0.3.1

Tried removing plugin and re-installing and made no difference. Is there a specific version I can force? Earlier in the day I played with 0.3.0 and that seemed to work fine.

**Comment by scampi** [comment]
Thanks for the report!

The version of kibana is hardcoded in the marvel plugin.
I managed to make marvel work by changing the plugin code.

Edit `installedPlugins/marvel/server/lib/ensure_versions.js` and update the field `2.2.0` in the `kbnVersionRanges` object to `^0.3.1`.

**Comment by scampi** [comment]
in the next release of kibi, this should be fix ;o)

**Comment by NTBTI** [comment]
Thanks that did do the trick. Now a new problem with Sense.....I'll post a new issue for that.
