### ISSUE TITLE
Sense plugin causing kibi_core not to start

### ISSUE THREAD

**Issue by NTBTI** [sirensolutions/kibi#17]
I installed the full demo of 0.3.1 and the Sense plugin and restarted Kibi.

Now on restart the kibi_core will not start causing every page of Kibi to go the the Status page.

The startup error is 
[info][status][plugin:kibi_core] Status changed from uninitialized to yellow - Initialising the query engine

But it never finished. If I remove the Sense plugin and restart the cache gets rebuilt and everything works again. But as soon as Sense is installed 0.3.1 stops working.

0.3.0 worked fine, but 0.3.1 is broken with Sense.

**Comment by scampi** [comment]
I am not able to reproduce this error. I downloaded the `Kibi Distribution` though, not the `Full Demo Distribution`.

**Comment by scampi** [comment]
sense works with kibi 0.3.2
