### ISSUE TITLE
How to achieve the drilldown function(Click handlers) as "Enhanced search results" plugin?

### ISSUE THREAD

**Issue by tommywsq** [sirensolutions/kibi#19]
Hi,

I would like to know how to achieve the drilldown function(Click handlers) like "Enhanced search results" plugin does?

**Comment by scampi** [comment]
In kibi you can perform drilldown operations on the dashboards using the ["relations filter"](http://siren.solutions/kibi/docs/current/relational-filter.html) visualization. This visualization adds buttons that enables to make joins between indices.

Click handlers in the [Enhanced search results](http://siren.solutions/kibi/docs/current/enhanced-search-results.html) visualization allow to:
- follow an URL
- select an entity

but no drilldown function is possible there.

For next time, please use the [kibi-user mailing list](https://groups.google.com/a/siren.solutions/forum/#!forum/kibi-users) for this kind of question. Github issues are only for bugs, feature requests, etc.

**Comment by tommywsq** [comment]
thanks a lot
