### ISSUE TITLE
Export to CSV from table visualisation

### ISSUE THREAD

**Issue by rubensr** [sirensolutions/kibi#20]
Hi are there any plans to include an "Export Raw/Formatted" feature to the table visualisation in Kibi? If not, is this something that you would consider including in Kibi if somebody submitted a pull request?

**Comment by scampi** [comment]
Kibana is working on that https://github.com/elastic/kibana/issues/1992
But feel free to propose other features ;o)

**Comment by rubensr** [comment]
Oh no I am not talking about the discovery tab (although that will be nice too) - I am talking specifically about the Kibi dashboard widget, the table visualization - currently it is an infinite scroll table, which is fine, but would be very very nice if the user could click on an "export to CSV" button to get the data as per the currently applied filters in the Kibi dashboard...

**Comment by szydan** [comment]
@rubensr - so such features are on our list, unfortunately at this point we can not give any ETA.

**Comment by scampi** [comment]
@rubensr I think the best is to wait for the feature I referenced landing in kibana. Then, a button could be added to the visualization you mentioned.

**Comment by rubensr** [comment]
Ah yes after going through the whole list of messages I think I get it - if the Kibana team can implement this server-side, then you can simply use them in your widget. That makes sense. Thanks for the very quick replies, and thanks so much for Kibi - this is really what elasticsearch needed to be used as a true analytics tool.

**Comment by scampi** [comment]
@rubensr Although it only allows to export the current set of document displayed, the 4.5.3-3 release https://github.com/sirensolutions/kibi/releases/tag/tag-4.5.3-3 contains a csv export for the `enhanced search results` visualization.
