### ISSUE TITLE
Kibi index NOT found

### ISSUE THREAD

**Issue by antong314** [sirensolutions/kibi#21]
Kibi 0.3.2 full demo version windows 64, getting below error frequently.  Suspect related to timeout, though not sure where one would increase it.

> log   [10:47:25.032] [error][status][plugin:elasticsearch] Status changed from green to red - Request Timeout after 1500ms
>   log   [10:47:32.124] [info][status][plugin:elasticsearch] Status changed from red to green - Kibana index ready
>   log   [10:47:33.171] [warning][query_engine] Kibi index NOT found
> H:\dev\Kibi-0.3.2\kibi-0.3.2-demo-full-windows64\kibi\src\plugins\kibi_core\lib\query_engine.js:90
>   self._isKibiIndexPresent().then(function () {
>        ^
> TypeError: undefined is not a function
>     at [object Object].QueryEngine.loadTemplates [as _onTimeout](H:devKibi-0.3.2kibi-0.3.2-demo-full-windows64kibisrcplugi
> nskibi_corelibquery_engine.js:90:8)
>     at Timer.listOnTimeout (timers.js:119:15)

Re-starting and navigating to the same page sometimes works.

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by szydan** [comment]
Should be fixed by https://github.com/sirensolutions/kibi/pull/24

**Comment by scampi** [comment]
@antongorshkov Please reopen if you still experience this issue.

**Comment by ecamaj** [comment]
After I modify this line, I constantly get:
log [11:37:22.876] [warning][query_engine] Kibi index NOT found
log [11:37:24.387] [warning][query_engine] Kibi index NOT found
log [11:37:25.899] [warning][query_engine] Kibi index NOT found
log [11:37:27.411] [warning][query_engine] Kibi index NOT found
log [11:37:28.921] [warning][query_engine] Kibi index NOT found
log [11:37:30.432] [warning][query_engine] Kibi index NOT found
log [11:37:31.947] [warning][query_engine] Kibi index NOT found
log [11:37:33.463] [warning][query_engine] Kibi index NOT found
log [11:37:34.976] [warning][query_engine] Kibi index NOT found
log [11:37:36.484] [warning][query_engine] Kibi index NOT found
log [11:37:37.995] [warning][query_engine] Kibi index NOT found
log [11:37:39.509] [warning][query_engine] Kibi index NOT found
log [11:37:41.021] [warning][query_engine] Kibi index NOT found
log [11:37:42.534] [warning][query_engine] Kibi index NOT found
log [11:37:44.043] [warning][query_engine] Kibi index NOT found
log [11:37:45.552] [warning][query_engine] Kibi index NOT found
...
