### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Brasoveanul** [sirensolutions/kibi#22]
Hello,

Congratulations for this very good Kibana fork. I have a few questions.
1. How could one change the logo that is displayed in the top left corner of the interface?
2. How could one eliminate some of the options that are displayed in the top menu bar, so that, for example, only the Discover menu is displayed?
3. Last, what is the procedure in order to install Kibana plugins in Kibi, for example Shield or Sense?

Thank you!

**Comment by scampi** [comment]
Thanks for the kind word!
1. not possible in kibi. But I think in Kibana 5 there is some work about that (to be checked, maybe this was just some comment). If I'm right, once we merge with kibana 5, we'll be able to as well.
2. in Kibana 5, they made these buttons as plugins, so you can easily remove one.
3. The procedure is the same as in kibana. For `Shield`, we are working on updating Kibi to support it. Please mail `info@siren.solutions` to know more.

**Comment by scampi** [comment]
In the future, please use the [mailing list](https://groups.google.com/a/siren.solutions/forum/#!forum/kibi-users) for these kinds of questions. We reserve Github for issues/feature request/etc.

**Comment by jccq** [comment]
Brasoveanul just to add to this if you want something quick you can certainly change the logo just replacing the files, everyone is doing it (you just dont have the nice option in the new). Other things can be haked also .. while we wait for the Kibana 5 based solution :) let us know in case, we can help

**Comment by Brasoveanul** [comment]
Hello,

What is the file that could be replaced in order to change the logo? Do you have any other suggestions regarding the top menu customization?

**Comment by jccq** [comment]
Please write to info @siren. Solutions I can respond from there about
specific support cheers
