### ISSUE TITLE
can not get the correct result on version 2.2.*

### ISSUE THREAD

**Issue by SolusNorth** [sirensolutions/kibi#23]
I have two index, DNS and UDP.
DNS has a field named address, UDP has a field named dip.
I want to join the index DNS and UDP with these field.

_**The correct result should be****:**_ After joined, the unique count of DNS and UDP should be equal. And the content of  DNS's field address and UDP's field dip should be equal too. 

when i was using ES2.1 and siren-join 2.1, i got the correct result
**THE RESULT OF DNS(correct)**
![image](https://cloud.githubusercontent.com/assets/8553667/14311345/658f4208-fc19-11e5-9734-48677428527a.png)

**THE RESULT OF UDP(correct)**
![image](https://cloud.githubusercontent.com/assets/8553667/14311425/0d34d4a0-fc1a-11e5-85d0-6aa911c1bdb4.png)

but, when i use ES2.2 and siren-join 2.2 or 2.2.0-1, the result was wrong
**THE RESULT OF DNS(wrong)**
![image](https://cloud.githubusercontent.com/assets/8553667/14311533/6de9f456-fc1a-11e5-8b00-9c59c31116ec.png)

**THE RESULT OF UDP(wrong)**
![image](https://cloud.githubusercontent.com/assets/8553667/14311555/94b9cc6e-fc1a-11e5-8dca-7f6996bb9b5e.png)

I mentioned that in version 2.1 you are using FieldDataTermsQueryHelper.hash , but in version 2.2.\* you change it into LongBloomFilter.hash3_x64_128. 
I 'm not sure if it is different that the way to use version 2.2.\* and version 2.1.\*  on kibi , Or the new algorithm of hash has a bug....

**Comment by SolusNorth** [comment]
I modified the code version 2.1.2,make it can be installed to ES2.2..
So now I am using ES2.2. with siren-join2.1.2, Then I joined the DNS and UDP again, the result is correct now. 
Maybe sometimes the new hash function LongBloomFilter.hash3_x64_128 will return the wrong result.

**Comment by jccq** [comment]
Hi there

yes you have hit the issue right. Kibi 0.3.2 introduced the Hash
capabilities which are absolutely great on huge datasets when you want
analutics but for small results it should not be activated.

We'll switch this off bin the next point release, apologies.

Notice the Kibi enterprise edition will have the ability to finetune this
for those who need.

Best
Gio

On Thu, Apr 7, 2016 at 8:00 AM, yangbaida notifications@github.com wrote:

> I modified the code version 2.1.2,make it can be installed to ES2.2..
> So now I am using ES2.2. with siren-join2.1.2, Then I joined the DNS and
> UDP again, the result is correct now.
> Maybe sometimes the new hash function LongBloomFilter.hash3_x64_128 will
> return the wrong result.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/sirensolutions/kibi/issues/23#issuecomment-206723857

## 

Giovanni Tummarello
CEO - SIREn Solutions

**Comment by szydan** [comment]
Please try the new community edition 4.4.1
https://github.com/sirensolutions/kibi/releases/tag/tag-4.4.1
In which bloom filter is NOT enabled by default
