### ISSUE TITLE
URIError: URI malformed  errors when building from source

### ISSUE THREAD

**Issue by nrasch** [sirensolutions/kibi#26]
All:

I'm working on building from source via these instructions:  https://github.com/sirensolutions/kibi/blob/master/CONTRIBUTING.md

When I execute "npm start" and attempt to browse to "http://localhost:5606/app/kibana" I receive a TON of these types of errors on the command line:

```
ERROR in ./src/ui/public/chrome/directives/app_switcher/app_switcher.less
    Module build failed: ModuleBuildError: Module build failed: URIError: URI malformed

ERROR in ./src/plugins/kibana/public/visualize/styles/main.less
    Module build failed: ModuleBuildError: Module build failed: URIError: URI malformed

ERROR in ./src/ui/public/styles/list-group-menu.less
    Module build failed: ModuleBuildError: Module build failed: URIError: URI malformed

```

And so on and so forth.  I've opened a few of these ".less" files and modified the "@import (reference)" statements with various file variations on the file path to no avail.

Is there is a solution for this, or perhaps I'm missing something?

Thanks,
Nathan

**Comment by scampi** [comment]
Probably this is the same error https://github.com/elastic/kibana/issues/6858
Please reopen if you still experience this error.
