### ISSUE TITLE
Sort option on fields in ehhanced search result not working

### ISSUE THREAD

**Issue by marfago** [sirensolutions/kibi#28]
Clicking on the arrow for the sort option on the column title in an enhanced result view dos not produce any effect.

**Comment by scampi** [comment]
I cannot reproduce this:

![output](https://cloud.githubusercontent.com/assets/795879/15108990/f3c9fc0e-15d0-11e6-8b12-7f458d1919b8.gif)

What system do you have ? Did you take the full or lite distribution ?
Is there anything in the logs, or in the web inspector, that might help ?

**Comment by marfago** [comment]
I'm with Kibi Version [0.3.2] - Powered by Kibana 4.4.1 for linux64 (ubuntu) and firefox 46.0.1. 
I checked the firebug console but did not find any error or warning.
There are 2 tables in the same pages, one work, but the other does not.
Is there anything I can do to help you to discover the bug?
May it be depending on number of rows in tabe (2502282)?

**Comment by scampi** [comment]
You have `2502282` rows showing in a table ? Could you show me the output of `curl 'http://localhost:9200/.kibi/config/_search'` ?

**Comment by scampi** [comment]
Do you have the same problem with Chrome ?

What is the output of `curl 'http://localhost:9200/.kibi/config/_search'` ?

Given the name of the field you were sorting on (`title`), I thought you were using the demo. But it seems I was wrong. Can you tell me more about that field ?
- analyzed ?
- how many docs in your index ?

**Comment by marfago** [comment]
It happens for all the fields in the table (dates, strings and numbers), in other words, no one is sortable (or sorted).
More, the working table is a common kibana's table, the other one not working is an enhanced table. The installation in a fresh one, using an index with 2.5M records. Debugging the code I can see that the sort function on the field is invoked correctly, then the "sorting" variable in changed accordingly with the case, but nothing happens afterwards. It looks like the watchCollection on "sorting" is not working.

**Comment by scampi** [comment]
Can you try to reproduce this with some data and share it in this issue ? That'll help a lot

**Comment by szydan** [comment]
@marfago could you please try 4.4.1
https://github.com/sirensolutions/kibi/releases/tag/tag-4.4.1

**Comment by scampi** [comment]
@marfago please reopen if this happens again
