### ISSUE TITLE
Unable to load "ace-sparql" modules because of a generic script error.

### ISSUE THREAD

**Issue by manalisha** [sirensolutions/kibi#3]
When we try to run the project using npm start[Already downloaded all node modules as well as bower components].

In require.config.js file:

 'ace-sparql': 'bower_components/ace-builds/src-noconflict/mode-sparql' --This is included.But this file doesnot exists in the bower module. And when we try to comment out the lines where this is being used..some other errors come from gridster.

SO we are currenty having problem to clone the project from this link of git hub and to run the application using node.

Elastic search is started.
Can you give us a solution to run the application from this clone code of KIBI.
![isue](https://cloud.githubusercontent.com/assets/4456244/10137836/3302cf94-6619-11e5-8aa9-4f46aa2f8db9.png)

**Comment by szydan** [comment]
In development mode you start the project by grunt 

```
npm install 
grunt dev
```

**Comment by manalisha** [comment]
Thanks. It is working now..Some how that file was missing ..Now it is present.
