### ISSUE TITLE
Support dark mode graph

### ISSUE THREAD

**Issue by bertol83** [sirensolutions/kibi#34]
Using dark theme, the graph is half white and half black.

![screenshot from 2016-05-24 10 29 31](https://cloud.githubusercontent.com/assets/13969336/15497324/7ca2d45e-219a-11e6-88d4-b9cf8a2da2ad.png)

**Comment by jccq** [comment]
yes still functional right? you mean just an aestetic issue? well open a
"Support dark mode graph" ticket

On Tue, May 24, 2016 at 9:31 AM, bertol83 notifications@github.com wrote:

> Using dark theme, the graph is half white and half black.
> 
> [image: screenshot from 2016-05-24 10 29 31]
> https://cloud.githubusercontent.com/assets/13969336/15497324/7ca2d45e-219a-11e6-88d4-b9cf8a2da2ad.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/sirensolutions/kibi/issues/34

## 

Giovanni Tummarello
CEO - SIREn Solutions
