### ISSUE TITLE
arrows to scroll tabs (dashboards)

### ISSUE THREAD

**Issue by bertol83** [sirensolutions/kibi#35]
Sometime when you have a lot of dashboards, the arrows (buttons) to scroll SX and DX tabs are hidden.
![screenshot from 2016-05-25 12 13 20](https://cloud.githubusercontent.com/assets/13969336/15536599/4dd93572-2272-11e6-9ca4-dc34f181cf5f.png)

**Comment by scampi** [comment]
Thanks, we are aware and plans to improve that are in the roadmap!

**Comment by szydan** [comment]
Fixed in 4.6.3-1
