### ISSUE TITLE
Feature request - export Relations objects

### ISSUE THREAD

**Issue by ecamaj** [sirensolutions/kibi#36]
In Settings->Objects there is no "Relations" tab which would enable us to export/import relations. This would be quite helpful having in mind that there can be many relations between indexes and that removing and creating instances of ELK stack is quite usual process in development.

**Comment by scampi** [comment]
This is in our roadmap. At the moment, it is available through the advanced settings, in the `kibi:relations` option.

**Comment by ecamaj** [comment]
Cool, thanks

**Comment by szydan** [comment]
fixed in 4.4.2-2
