### ISSUE TITLE
Relational Panel Configuration

### ISSUE THREAD

**Issue by dwong61** [sirensolutions/kibi#37]
Hello,
The Relational Panel configuration seems to be intuitive but I can't seem to configure the left/right panel relationship. I've configured the index pattern relations and the labels appear in the label selection in the Relational Panel configuration widget, but the dash board selection remains empty (I have two dashboards defined for the related indices). 

Sorry about the doc. I'll try it again.
The fields are the same type: string, not_analyzed.

Sorry about the doc. I'll try again.
The fields are the same type: string, not_analyzed.

[Kibi_issue.zip](https://github.com/sirensolutions/kibi/files/290026/Kibi_issue.zip)

**Comment by scampi** [comment]
your doc didn't get uploaded. you have to wait a bit before sending the post

**Comment by scampi** [comment]
make sure the fields you are joining on have the same mapping #32

**Comment by dwong61** [comment]
Sorry about the doc. I'll try again.
The fields are the same type: string, not_analyzed.

[Kibi_issue.zip](https://github.com/sirensolutions/kibi/files/290027/Kibi_issue.zip)

**Comment by scampi** [comment]
You need to save your dashboard with a saved search. Then, you will be able to see the dashboards that were associated with a saved search in the relations settings page. To do so, just click on the save button of a dashboard, and then select a saved search in the dropdown menu.

Also, I see that you are using an old version. You can have a taste of the latest things (+ bug fixes) with Kibi 4.4.1-1

**Comment by dwong61** [comment]
Hello Scampi,

Thanks for the reply. The dashboards were saved and I can seen the dashboards when I look at available objects in the settings menu. Also, using Head, I can see the dashboard documents in the .kibi index. I did try using the latest Kibi version (4.4.1-1), where the Relational Panel configuration menu is in separate configuration panel tab, same behavior. It just seems like the app isn't picking up the correct ElasticSearch documents. Is there some permission related issue? I've tried setting everything to the same owner/group as well as setting all (that I know of) file permissions to 777.

Here is what I've tried:

1) Download the full demo, setup and make sure it runs correctly.
2) Able to see the dashboards when attempting to configure the Relational Panel
3) Delete all ElasticSearch indices, including Kibi, using Head
4) Restart Kibi and make sure a new Kibi index is created
5) Re-populate ElasticSearch with my own indices.
6) Browse the ElasticSearch indices using head to make sure everything is correct
7) Attempt to configure relationships
8) Everything works except Relational Panel configuration where dashboards does not appear in the selection pull-downs.

What role does Siren-Join play? I have it installed in the older version that uses ElasticSearch 2.2. Is it required for the latest 4.4.1-1?

**Comment by scampi** [comment]
Is this Head https://github.com/mobz/elasticsearch-head ?

SIREn Join is used for performing joins between indices. It is needed in kibi only if you want to do joins, e.g., the relational filters.

I think I was not clear in my reply. In the Dashboard panel, open a dashboard and then save it. You will see something like below:
![2016-05-31-172259_1893x290_scrot](https://cloud.githubusercontent.com/assets/795879/15682226/a24372a8-2754-11e6-8f63-e407094926eb.png)
At this point, set the saved search you want and save.

**Comment by dwong61** [comment]
Thank you. I will try this.

**Comment by dwong61** [comment]
Hello Scampi,

That was what I was doing with both dashboards so I'm not sure how to proceed. I will clean everything up and try again.

**Comment by scampi** [comment]
Can you share the output of the following command:

```
curl 'localhost:9200/.kibi/dashboard/_search' 
```

**Comment by dwong61** [comment]
Here it is:

[dashboard.txt](https://github.com/sirensolutions/kibi/files/292242/dashboard.txt)

**Comment by scampi** [comment]
Neither `Observables` nor `Indicators` have a field named `savedSearchId`. This field should be added when you save a dashboard as described in my comment with the image.
Did you get any errors in the logs (or web inspector) when you did so ?

**Comment by dwong61** [comment]
I don't belief I got any errors. I'll double check. Do you mean the Kibi or ElasticSearch logs?

**Comment by dwong61** [comment]
I just modified the Indicators dashboard and saved. Has Kibi log verbose enabled and also watching the browser. No warnings or errors indicated

**Comment by dwong61** [comment]
Okay. The problem is that I have not defined a query associated with the dashboard. Are there any example or docs you can point me to for a dashboard associated query?

**Comment by scampi** [comment]
http://siren.solutions/kibi/docs/current/dashboard.html
you need to set a saved search first

**Comment by dwong61** [comment]
Thank you Scampi !! I just did that.
