### ISSUE TITLE
The dashboard search bar did not work.

### ISSUE THREAD

**Issue by sarufarr** [sirensolutions/kibi#38]
Here is condition: I have set up the kibi default dashboard("dashboard-One") in the kibi.yml. 

If I type in the URL: 192.168.0.1:5601 ("locahost:port") into the browser address bar, the kibi jumped to "dashboard-One" as I expected. 

But the dashboard search bar did not work whatever I type in at this time. 

And the search bar would work properly after I chose the DISCOVER page and went back to DASHBOARD page.

Looking forward to hearing from you soon.

**Comment by scampi** [comment]
Is this with the latest kibi ? What OS do you have ?

**Comment by sarufarr** [comment]
No. The version of kibi I am using is 0.3.2.
OS: CentOS 6.7
broswer: chrome latest

**Comment by scampi** [comment]
it does not seems to happen with the latest version of kibi (4.4.1-1). Please try again with that.

**Comment by szydan** [comment]
reopen if it happens again
