### ISSUE TITLE
count on relational buttons

### ISSUE THREAD

**Issue by bertol83** [sirensolutions/kibi#39]
### Versions

Kibi: 0.3.3 biuld n. 8971

Operating System: ubuntu 14.04
### Behavior

The count on relational buttons seems not work as expected.
### Steps to reproduce the problem
1. Start from a dashboard without filters.
2. The buttons have just (*)
3. Select a filter
4. The count is updated
5. Remove filter and the count is updated (with all documents from other indexes)
6. Refresh page and the count is again (*)

[out-2.ogv.zip](https://github.com/sirensolutions/kibi/files/290982/out-2.ogv.zip)

**Comment by scampi** [comment]
@bertol83 do you have any stack trace in kibi logs/web inspector ?
It seems that the join failed for some reason, but i'd need more information about your setup to reproduce this.

**Comment by scampi** [comment]
cannot reproduce on the latest version 4.4.1-2
