### ISSUE TITLE
Question - Cherry picking visualisations

### ISSUE THREAD

**Issue by coreation** [sirensolutions/kibi#4]
Hi!

I'm really impressed with what Kibana can come up with and how Kibi extends it, my question is about taking the visualisations a step further. 

Currently, Kibana and Kibi provide a user interface to manage queries and make visualisations out of it, great! But what if I were only to present the visualisations to others, in order to integrate it with a website or web app. So, the people viewing the vis. don't need to manage the query themselves or indulge themselves into the Kibana (Kibi) Web UI, but only see a useful graphical representation of data. 

Is such a thing possible (or with another jQuery based platform on top of ES perhaps)? If my question is not clear, compare it with youtube and their embed urls, but then for Kibana (Kibi).

**Comment by coreation** [comment]
Ok apparently, as with any question, I should have googled it. Kibana has a feature to share a visualization. Is this feature also available in Kibi?

**Comment by fabiocorneti** [comment]
Hi @coreation, in both Kibana and Kibi it is possible to share a dashboard by embedding it; to display the embedding code, just click on the share button:

![image](https://cloud.githubusercontent.com/assets/32792/10248921/d63de5ca-6922-11e5-96cb-69d73a1cd0ba.png)

**Comment by coreation** [comment]
Awesome stuff, feeling really lazy for not having googled it before posting, sorry :). 
Definitely going to get started with this!

**Comment by fabiocorneti** [comment]
There are security implications as viewing a shared dashboard requires access to Kibana, so you should ensure that the Elasticsearch index is read-only to anonymous users.

**Comment by coreation** [comment]
Thanks for the heads-up!
