### ISSUE TITLE
timeline after selection

### ISSUE THREAD

**Issue by bertol83** [sirensolutions/kibi#40]
### Versions

Kibi: Kibi: 0.3.3 biuld n. 8971

Operating System: ubuntu 14.04 64 bit
### Behavior

The timeline doesn't show events and states after an aggregation filter 
#### Expected:

The timeline should show the events also after a filter 
### Steps to reproduce the problem
1. Dashboard without filter show timeline with first 10 (configured) events for each index.
2. Select some documents by Data Table
3. The timeline does't show anything.
4. After remove the filter timeline show again events/states
   [out-2-1.ogv.zip](https://github.com/sirensolutions/kibi/files/291081/out-2-1.ogv.zip)

**Comment by scampi** [comment]
opened in timeline repo https://github.com/sirensolutions/kibi_timeline_vis/issues/23
