### ISSUE TITLE
duplicate relational filters in filter bar

### ISSUE THREAD

**Issue by nreese** [sirensolutions/kibi#41]
### Versions

Kibi: 4.4.1

Operating System:

osx 10.10.3
### Behavior

Duplicate relational filters displayed in filter bar
#### Expected:

When using the Relational Filter visualization to browse to another dashboard, kibi should recognize duplicate relational filters and keep only one.
#### Actual:

Duplicate Relational filters apear in filters bar.
### Steps to reproduce the problem

With kibi demo version, start in Articles dashboard. Use the `Companies --> ()` button provided in the Relational Filter visualization to browse to the Companies dashboard. As expected, the Companies dashboard is displayed with one filter. 

Use the navigation tabs to browse back to the Articles dashboard.

Use the `Companies --> ()` button provided in the Relational Filter visualization to browse to the Companies dashboard. Wow... why are there now duplicate `As mentioned in Articles` filters in the filters bar?

**Comment by jccq** [comment]
The meaning of a "Relational button" is "add a filter in the other dashboard to filter only to those connected to the current ones" .. 

it is not a "navigational button" (The tabs are for navigations). 

It is useful that the buttons create different filters, for example you might look for articles that mention "foo" and check all the companies. Then you might go back and look for articles mentioning "Bar" and go forward". At this point you have 2 rel filters, one coming from foo search and one coming from bar search, giving you the intersection of the 2 sets of companies.  (works better on less trivial examples)

This is why the "relational panel" and the "relational buttons" are differeny. The relational panel wont allow these level of "back and forth" queries. 

I do see that a person might mistake the --> for a navigational button.

Maybe we could have a message saying "your target dashboard alrady have a filter coming from this, woudl you like to keep both or replace previous with this?"

this is somewhat similar to the message one gets when you click on a nested aggregator slice.

what do you think?

**Comment by nreese** [comment]
I did not fully understand how the relational filters worked. I assumed
that the relational filter linked the two indices together and any future
filter applied to one index would affect the other.  I did not realize that
the relational filter only applies the currently active filters and ignores
any future filters. I can see why one would want multiple filters with the
current behavior.

I think a warning message would just annoy experienced users and maybe
further confuse novice users.

The current GUI provides lots of potential to confuse novice users.
Unfortunately, I do not have any useful suggests to help clear the mud. Let
me play around with kibi for a couple weeks and I will get back to you if I
can think of anything useful.

Nathna

**Comment by jccq** [comment]
Great :) thanks. We definitely have to do something abou thtis e.g. creating a Kibi user academy video series etc. The power , in the end, is really big. . Do let us know! also have you considered http://siren.solutions/kibi/enterprise ? the graph is a pretty interesting addition as it interacts directly with the dashboards. best
