### ISSUE TITLE
Relational filter run out of an exception when i was using it on cluster

### ISSUE THREAD

**Issue by SolusNorth** [sirensolutions/kibi#44]
### Versions

Kibi: 0.3.2

siren-join: 2.1.2 or a higer version but not use bloom filter

Operating System:  CentOS6.7
### Behavior

the siren-join plugin can not find data-node in cluster
#### Expected:

![catch 06-16-14-21-21](https://cloud.githubusercontent.com/assets/8553667/16107843/8faad8fa-33d1-11e6-83ff-b5bec528d71d.jpg)
#### Actual:

the cluster is working well, its status is green. but when i am trying to use Relational filter, this exception will be accured.
**This situation will not happen when i just have only one node.**
### Steps to reproduce the problem

set up a cluster with elasticsearch2.2.0
client-node: 1
master-node:3
data-node:3
3 shards  1 replica
each node has a siren-join plugin, a head plugin ,and a bigdesk,  kopf . sql 

connect kibi  to the client-node, then use the Relational filter.

**Comment by scampi** [comment]
Can you try to reproduce this with the new version 4.4.2 ? Thanks

**Comment by scampi** [comment]
Please reopen if you still have this problem with https://github.com/sirensolutions/kibi/releases/tag/tag-4.5.3
