### ISSUE TITLE
Compatibility with ES 1.7.2

### ISSUE THREAD

**Issue by gioialorusso** [sirensolutions/kibi#45]
### Versions

Kibi: 4.4.2
Operating System: OSX el capitan 10.11.3 
ES: 1.7.2
### Behavior

My version of elasticsearch is incompatible with this version of Kibi. I'd like to know what version of Kibi can I install that is compatible with ES 1.7.2
#### Actual:

Status changed from red to red - This version of Kibana requires Elasticsearch ^2.2.0 on all nodes. I found the following incompatible nodes in your cluster: Elasticsearch v1.7.2 @ inet[/192.168.1.79:9200](192.168.1.79)

**Comment by scampi** [comment]
https://github.com/sirensolutions/kibi#compatibility-table-kibi--elasticsearch kibi 0.2.0 then
