### ISSUE TITLE
Find identical field values from different indexes

### ISSUE THREAD

**Issue by tombimbom** [sirensolutions/kibi#46]
Is it possible to find identical field values from different indexes and list the corresponding files? Let's say I have two syslogs and I need to find the IP addresses that occur in both logs. Is that possible to do with kibi? 

Thanks a lot.

**Comment by scampi** [comment]
If the IP is a field of your indices, you could join the two on that field. See http://siren.solutions/kibi/docs/current/relational_filter.html

**Comment by scampi** [comment]
In the future please reserve github for issues/new features/ etc.
For this kind of question, please use https://groups.google.com/a/siren.solutions/forum/#!forum/kibi-users.

**Comment by tombimbom** [comment]
Dear Stéphane, thank you and sorry for posting in the wrong place.

**Comment by scampi** [comment]
No problem. If you still have some issues, please open a thread in the mailing list to follow on that.
