### ISSUE TITLE
TypeError: Cannot read property 'byName' of undefined

### ISSUE THREAD

**Issue by mike-marcacci** [sirensolutions/kibi#47]
### Versions

Kibi: 4.4.2 and master

Operating System: OSX 10.11.5
### Behavior:

More often than not (but still not _always_) the "Discover" tab errors out with `TypeError: Cannot read property 'byName' of undefined`. Kibana 4.4.2 has no such issue when using the exact same ES cluster.
#### Expected:

![screen shot 2016-06-21 at 10 02 54](https://cloud.githubusercontent.com/assets/690517/16239015/cbc7de40-3797-11e6-8431-650e6de07522.jpg)
#### Actual:

![image](https://cloud.githubusercontent.com/assets/690517/16238844/fd913882-3796-11e6-8180-807baa5212de.png)
### Steps to reproduce the problem

Go to "Discover" tab.

**Comment by scampi** [comment]
It seems that `fields` in the `indexPattern` object is not defined. https://github.com/sirensolutions/kibi/blob/75d8098/src/ui/public/doc_table/lib/get_sort.js#L16

Logs: Is there anything in the ES logs or kibi logs ?
Somehow the fields for that index pattern could not be retrieved.

Is the kibi 4.4.2 instance built from scratch, or did you migrate a previous one ?

**Comment by scampi** [comment]
Can you reliably perform several times the following request on your ES cluster ?

``` sh
$ curl -XGET 'http://localhost:9200/.kibi/index-pattern/<YOUR_INDEX>?_source=fields' 
```

**Comment by scampi** [comment]
Please reopen the issue if you still have problems and provide some logs.
