### ISSUE TITLE
kibi-icons missing in npm

### ISSUE THREAD

**Issue by vinuja** [sirensolutions/kibi#48]
### Versions

Kibi_timeline_vis-4.4.2

Kibi:

Operating System:
### Behavior

Unable to manually install Kibi_timeline_vis .
#### Expected:

 Kibi_timeline_vis needs kibi-icons.In npm this library is missing.

Can you add it please

**Comment by scampi** [comment]
Try again to download https://github.com/sirensolutions/kibi_timeline_vis/releases/download/4.4.2/kibi_timeline_vis-4.4.2.zip
The tarball was not correctly done.

**Comment by vinuja** [comment]
Thanks 
It works now
