### ISSUE TITLE
Kibi hangs on start on Windows x64 with JDBC enabled

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [sirensolutions/kibi#52]
### Versions

Kibi: 4.4.2.1

Operating System:
Windows 7/Server 2008 R2 x64 or greater
## Problem

After setting `kibi_core.load_jdbc: true` kibi does not start.

CPU spins and command line reads:

```
Checking jdbc_enabled flag in <My install folder>
Detected jdbc_enabled: [true]
```
## How I fixed it
1. Ensure JAVA_HOME is set to your program files java folder
2. Add an empty file named `javac.exe` to `%JAVA_HOME%\bin`
## Comments

Hello all, I had this issue trying to start Kibi with `kibi_core.load_jdbc: true` set in my kibi.yml file.
I spent some time on google and found some details about a workaround that disabled JDBC but allowed kibi to start on windows x64. But i needed JDBC, so i did some research and think i have a fix.

The issue at it's heart is that Kibi uses node package `JDBC` which uses ultimately `Find-Java-Home` npm package.

After fiddling with the package installation and eventually looking at the source code i discovered that this package locates the java home directory by:
1. Does `JAVA_HOME` env variable exist
2. If so does the path `%JAVA_HOME%` actually exist on disk
3. If so does `%JAVA_HOME%\bin\javac.exe` exist on disk

**My fresh Java 8 x64 installation does not have javac.exe**

I created an empty file at this location and Kibi loaded just fine with the JDBC driver i configured.

Hopefully this workaround helps someone who comes googling.

**Comment by scampi** [comment]
Thanks @AlgorithmsAreCool for taking the time to describe the problem and your fix!

I don't have a windows machine, can you tell me what is inside `%JAVA_HOME%\bin\` ? Maybe we can propose a fix upstream.

**Comment by AlgorithmsAreCool** [comment]
I have opened an upstream issue in hopes of a simple fix in time. The contents on the `%JAVA_HOME%\bin\` are listed on that issue.

**Comment by AlgorithmsAreCool** [comment]
Also, i need to fiddle with Kibi some more to figure out exactly how to work with relational data, but it appears that everything works OK with MSSQL via Microsoft's JDBC driver. :+1:

**Comment by scampi** [comment]
Thanks @AlgorithmsAreCool
