### ISSUE TITLE
tilemap isn't zooming more than 8 levels

### ISSUE THREAD

**Issue by yaacovki** [sirensolutions/kibi#54]
### Versions

Kibi: 4.4.2-1

Operating System:
Linux
### Behavior

When using WMS complaint map (like defined in fix bug on the 13 of july) 
the map is zooming till some level, and then the Plus + button is going gray and i can't zoom anymore

The behavior is like i have 7-8 level of zoom only...
#### Expected:

In other environment (Windows 64 bit) with kibi 4.4.2 the zoom is working fine

**Comment by scampi** [comment]
Can you try with the latest release 4.5.3 to see if this is still happening ?

**Comment by yaacovki** [comment]
upgraded to 4.5.3 still happens - Tilemap not going over level 7-8 zoomin

**Comment by yaacovki** [comment]
hi,
Once i've applied the WMS complaint map it works
how can i change the default maps to be Terrestris.de?

**Comment by scampi** [comment]
Maybe the answer you are looking for is at https://www.elastic.co/guide/en/kibana/current/tilemap.html under `WMS compliant map server`.

**Comment by scampi** [comment]
@yaacovki please reopen if you still have a problem.
