### ISSUE TITLE
layout issue

### ISSUE THREAD

**Issue by scampi** [sirensolutions/kibi#57]
If I click the option button of the visualization window in Dashboard.
(Just the "Pen" beside the delete button "Close" on the left-top of the visualization window.)
The whole Dashboard page will change into white first and jumped into Visualize page.
And then if I click the Dashboard button to jump back to Dashboard page, I notice the visualization window shape changed. It seems that your dashboard layout adaptive algorithm goes wrong. After I refresh the whole page, the layout become correct again.

taken from https://github.com/sirensolutions/kibi/issues/55

**Comment by scampi** [comment]
Can you make a gif of the issue ? @nvrdawn

**Comment by sarufarr** [comment]
![dashboardviserror](https://cloud.githubusercontent.com/assets/14183804/18120729/8db2cdca-6f93-11e6-9db4-ffdf79f59e0d.gif)
Here it is. White dashboard before page jumps into visualization did not appear this time. But layout did have something wrong.

**Comment by scampi** [comment]
issue upstream https://github.com/elastic/kibana/issues/6786
