### ISSUE TITLE
Cant delete previous relations

### ISSUE THREAD

**Issue by davidandorf** [sirensolutions/kibi#58]
### Versions

Kibi: I cant delete relations ships they seem to be stuck which is also not aloowing me to add any other relations, Any possible way to refresh kibi?

Operating System:

**Comment by jccq** [comment]
Hi in the advanced settings tab you can find all the relations and a job
blob . Just delete there

However wr have never seen this would you be kind and try to reproduce step
by step?  Alternatively before deleting the json blob can u send it over
for us to debug the strange state you're in?

Also are you sure you are using the latest version?

**Comment by scampi** [comment]
what version of kibi are you using ? can you share a gif of the problem, that could help understanding the issue ?
Also, did you install a fresh kibi, or did you a previous version already ?

**Comment by scampi** [comment]
Please reopen the issue if it still happens.
