### ISSUE TITLE
Inconsistent numbers from scratch and when filters are applied

### ISSUE THREAD

**Issue by stefanobortoli** [sirensolutions/kibi#59]
### Versions

Kibi: 4.5.3-4

Operating System:

Server Ubuntu 14.04-LTS, Browser Chrome 53.0.2785.116 m on Win 7 Pro
### Behavior

Relational widget presents different numbers when applying sequential filters. In particular, the same object appears to have relations when filtered with a query on the top search box, and the same object did not have any relation when filtered using one of its properties.
#### Expected:

consistency in the relational widget up on different ways to filter the same object.
#### Actual:

the number of relations with other dashboard changes according the way we filter the same object.
### Steps to reproduce the problem

attached the screencast: http://recordit.co/Nnm1dwlICE

**Comment by rendel** [comment]
Hi Stefano, could you send the configuration of your relations ? In particular the terms encoding parameter for each of your relation. Thanks.

**Comment by bertol83** [comment]
This Kibi should be the Community Edition, so I think the terms encoding is fix to long.

**Comment by stefanobortoli** [comment]
It is the Enterprise version.

**Comment by bertol83** [comment]
Ok, so go on Settings --> Relations and press on the grey pen for your relation
![image](https://cloud.githubusercontent.com/assets/13969336/18916030/e2d385e4-858a-11e6-9176-ae2285458434.png)

and copy here your config

**Comment by stefanobortoli** [comment]
attached all the screenshots I thought could be helpful

![veicoli-index-conf](https://cloud.githubusercontent.com/assets/6428160/18916269/3377d424-8594-11e6-944d-92d33e1af88f.png)
![conf-relations](https://cloud.githubusercontent.com/assets/6428160/18916268/336304f4-8594-11e6-8ddb-7540633ae26d.png)
![formalita-index-conf](https://cloud.githubusercontent.com/assets/6428160/18916266/335cf4a6-8594-11e6-97ba-d2b6bbc8c588.png)
![relations-28092016](https://cloud.githubusercontent.com/assets/6428160/18916267/3363e0c2-8594-11e6-9a75-03e0ff839f75.png)

**Comment by rendel** [comment]
And if you click on the button (when it is count is equal to 1) to go to formalita, what is the result ? Is there one formalita document on the dashboard, or 0 ?

**Comment by stefanobortoli** [comment]
The filter says: "related to 2 from Veicoli", but the dashboard is empty.

**Comment by stefanobortoli** [comment]
![formalita-vuota](https://cloud.githubusercontent.com/assets/6428160/18916777/ddb2ed7e-8595-11e6-8ea3-56b8f9c39b07.png)

**Comment by scampi** [comment]
what is the configuration of those buttons ?

**Comment by scampi** [comment]
In the next release, the relational filter visualization will have a spy panel, but for now the only way to get the queries behind it is through the dev inspector.
Can you check what is the query sent ? It is one which name contains `button` so the easy way to get it is to type `button` in the request filter (if you use chrome).

**Comment by stefanobortoli** [comment]
ok, about the the previous questions: when there is 1 on the button of the relational widget (filter by plate number) and I click on it, I have a dashboard formalita with 1 object with the relation of 1 vehicle. When I click on the button with count 0 (filter by vehicle id number), then I have the empty dashboard with the message of 2 vehicle.

**Comment by stefanobortoli** [comment]
if you need, we could share the whole bundle privately.

**Comment by scampi** [comment]
if possible that'd be nice

**Comment by stefanobortoli** [comment]
how can I send the bundle? it is around 250MB

**Comment by bertol83** [comment]
You should receive an email. I have shared a folder with you on google drive

**Comment by stefanobortoli** [comment]
I was doing the same, already uploading. I will either share that or upload
here tomorrow morning.

Thanks a lot for the support!

Il 28 set 2016 6:38 PM, "Nicola" notifications@github.com ha scritto:

**Comment by jccq** [comment]
guys this should be a ticket in the Customer Portal for the EE :)?

**Comment by stefanobortoli** [comment]
We can move it there. No problem. I have just shared the bundle with Nicola.

**Comment by stefanobortoli** [comment]
We restarted kibi, and for some obscure reasons the problems were solved. We keep it monitored to understand whether the problem appears again. Thanks a lot for the quick response and valid support received.

**Comment by rendel** [comment]
Hi @stefanobortoli, before seeing this issue, were you sending updates to the indices (e.g., adding or removing some documents) while Kibi was running ? (I am just wondering is this was not a caching issue somewhere).

**Comment by stefanobortoli** [comment]
I think so. Kibi was on while indexing the snipped of data used for the analysis.

**Comment by rendel** [comment]
If this happens again, could you try to run the command to clear the siren join cache:

```
$ curl -XGET 'http://localhost:9200/_filter_join/cache/clear
```

And then reload the kibi dashboard and see if the count changes as expected.
If this is the case, please report this to us. Thanks.

**Comment by stefanobortoli** [comment]
I will certainly do. I guess the restart does the clear, right?

**Comment by rendel** [comment]
Restarting elasticsearch yes. But if you restarted only Kibi, then this means this is something on Kibi side, not siren join side. Did you restart Kibi or elasticsearch ?

**Comment by stefanobortoli** [comment]
We restarted everything, so we cannot help on this. However, we'll try to keep trace of these operations so that if we have troubles we can report.
