### ISSUE TITLE
how to use spark as my external datasaource?

### ISSUE THREAD

**Issue by asinha123** [sirensolutions/kibi#6]
Hi, I am able to connect mysql database as an external datasource. But is there a way to use spark as my external datasource?

**Comment by fabiocorneti** [comment]
It should be possible to query Spark SQL module by configuring a JDBC datasource; a commented JDBC datasource is defined in the `kibi.yml` file around line 93.

**Comment by asinha123** [comment]
Hi,
I have tried but it is not working with the following configuration

mysql-jdbc-datasource:
    type: jdbc
    #libpath: "/ABSOLUTE/PATH/TO/mysql-connector-java-5.1.35-bin.jar"
    libpath: "/home/bedrock/vis/calliope-jdbc-assembly-1.1.0-CTP-U2.jar"
    drivername: "org.apache.hive.jdbc.HiveDriver"
   # url: "jdbc:mysql://HOST/DATABASENAME"
    url: "jdbc:hive2://MY-IP-PORT/xademo"
    libs: []
    user: 'username'
    password: 'password'

Running the query is not retrieving any response and also not throwing any exception in kibi log.

But but but

somehow I am  able to retrieve data in query section performing the following action

filepath: server/lib/sindicetech/jdbcQuery.js

method name: JdbcQuery.prototype.fetchResults

commenting out from line # 127 to # 139 and  # 204 is resolving our issue.

Please give me the right way to handle it.

Please help.

**Comment by fabiocorneti** [comment]
Looks like a caching bug, we'll try to reproduce it internally; in the meantime, you could try do disable caching by setting `datasource_enable_cache` to `false` in `kibi.yml` instead of commenting the lines, should have the same effect.

**Comment by szydan** [comment]
In 0.3.0 the jdbc datasource was improved.
Could you try to verify that this is still happening.

Note: in 0.3.0 the parameters should be 

```
libpath: "/home/bedrock/vis"
libs: "calliope-jdbc-assembly-1.1.0-CTP-U2.jar"
```

libs - is now comma separated list of libs (paths either relative to libpath folder or absolute)

**Comment by scampi** [comment]
@asinha123 Please reopen if you encounter some issues again.
