### ISSUE TITLE
Query template error

### ISSUE THREAD

**Issue by txisme** [sirensolutions/kibi#61]
### Versions

Kibi: 4.5.3

Operating System: CentOS
### Behavior

I want to create a templated query.
#### Expected:

To Create a templated query
#### Actual:

It shows the error: "Query deactivated. Check activation query or change entity URI"

![image](https://cloud.githubusercontent.com/assets/10253258/19438006/b3f5e624-946f-11e6-9baa-f929b53ae3a7.png)
### Steps to reproduce the problem

Just follow the tutorial from siren solutions website
http://siren.solutions/showing-the-latest-values-in-kibikibana-say-hi-to-the-rest-datasource/

**Comment by scampi** [comment]
This was for Kibi v0.2 , maybe there is something that changed since then. I'll try to see what could be the cause.

**Comment by txisme** [comment]
Ok, thank you

**Comment by atifelkhachine** [comment]
![image](https://cloud.githubusercontent.com/assets/23389146/20195021/22bdc418-a795-11e6-9a4d-669b802f2694.png)

`span !{results.hits.hits[0].fields.time}
br
span !{results.hits.hits[0].fields.conditions}`

This should work. results object is not an array ;-)

Atif EL KHACHINE

**Comment by szydan** [comment]
@atifelkhachine Thank you for the feedback.
