### ISSUE TITLE
Bug: apply already in progress

### ISSUE THREAD

**Issue by hwkongsgaard** [sirensolutions/kibi#65]
### Versions

Kibi: 4.5.4 (build: 12601), standalone 

Operating System:
Ubuntu

### Behavior 
Hi, when I save a new datasource (REST) or edit it I get this error when I hit save

[$rootScope:inprog] $apply already in progress http://errors.angularjs.org/1.4.8/$rootScope/inprog?p0=%24apply (http://10.1.62.2:5606/bundles/commons.bundle.js?v=12601:43878)

The object i saved if I go back, but the preview is not showing

**Comment by scampi** [comment]
@hwkongsgaard can you see if that still happens with the new release ? thanks

**Comment by scampi** [comment]
Please reopen the issue if it still happens.

**Comment by scampi** [comment]
in the latest release (4.6.4) thanks
