### ISSUE TITLE
Relations in the same index

### ISSUE THREAD

**Issue by olidem57** [sirensolutions/kibi#66]
### Versions

Kibi: 4.6.3

Operating System: Ubuntu 14.04 (LTS)

### Behavior 

We're trying to configure a relation between two types. It's working well when these types are indexed in two distinct indices but not anymore when they're indexed in the same index.

I noticed something weird in the advanced settings, an inversion seems to occur. This is our relation: 
<img width="1159" alt="screen shot 2017-01-02 at 17 05 09" src="https://cloud.githubusercontent.com/assets/5486003/21592422/b674b3fa-d10d-11e6-8293-88c3b874070f.png">

This is the "kibi:relations" setting : 
<img width="674" alt="screen shot 2017-01-02 at 17 06 38" src="https://cloud.githubusercontent.com/assets/5486003/21592451/ddb71246-d10d-11e6-8e85-342952e28e74.png">

When I change the order of the parameters in the id field (and its references) the relations works !
![settings kibi](https://cloud.githubusercontent.com/assets/5486003/21592635/681b730e-d10f-11e6-90ca-00219f9ebdcb.png)

Is it possible to work with different types in the same index ?

**Comment by scampi** [comment]
This feels like a bug, the order should not matter. I'll have a look. Did you start from a plain kibi, or did you upgrade from an existing installation ? Or anything else special ?

> Is it possible to work with different types in the same index ?

Normally yes

**Comment by olidem57** [comment]
It's a fresh install without any upgrades, I don't think there's anything special

**Comment by olidem57** [comment]
Here's something that might help you.

I created a new relations, between two distinct indices, from "ct_tada_family_situation" to "ct_tada_full_text" (the last one is the primary index, don't know if that's relevant or not) : 
<img width="1168" alt="screen shot 2017-01-05 at 13 38 54" src="https://cloud.githubusercontent.com/assets/5486003/21680855/92bde0c6-d34c-11e6-96cd-eda459a27372.png">

I then configured the relation filter like that : 
<img width="833" alt="screen shot 2017-01-05 at 13 41 49" src="https://cloud.githubusercontent.com/assets/5486003/21680963/15248e48-d34d-11e6-823d-5cbc9198aa7a.png">

Which doesn't seem to work in my dashboard : 
<img width="432" alt="screen shot 2017-01-05 at 13 45 05" src="https://cloud.githubusercontent.com/assets/5486003/21680983/342c15cc-d34d-11e6-9174-e26db49d14a9.png">

When I click this button I can see the following filter activating : 
<img width="469" alt="screen shot 2017-01-05 at 13 46 17" src="https://cloud.githubusercontent.com/assets/5486003/21681001/5c6ba516-d34d-11e6-8e52-d5aec2629198.png">

Here's the full JSON : 
```
{
  "join_sequence": [
    {
      "relation": [
        {
          "pattern": "ct_tada_full_text",
          "path": "id",
          "indices": [
            "ct_tada_full_text"
          ],
          "queries": [
            {
              "query": {
                "bool": {
                  "must": [
                    {
                      "query": {
                        "query_string": {
                          "analyze_wildcard": true,
                          "query": "*"
                        }
                      }
                    },
                    {
                      "query": {
                        "query_string": {
                          "query": "_type:familysituation",
                          "analyze_wildcard": true
                        }
                      }
                    }
                  ],
                  "must_not": [],
                  "filter": {
                    "bool": {
                      "must": []
                    }
                  }
                }
              }
            }
          ],
          "termsEncoding": "long",
          "types": [
            "person"
          ]
        },
        {
          "pattern": "ct_tada_family_situation",
          "path": "pupil_contacts.id",
          "indices": [
            "ct_tada_family_situation"
          ],
          "termsEncoding": "long",
          "types": [
            "familysituation"
          ]
        }
      ]
    }
  ]
}
```

Once again some inversion seems to occur, if I change the JSON to this one : 
```
{
  "join_sequence": [
    {
      "relation": [
        {
          "pattern": "ct_tada_family_situation",
          "path": "pupil_contacts.id",
          "indices": [
            "ct_tada_family_situation"
          ],
          "termsEncoding": "long",
          "types": [
            "familysituation"
          ],
          "queries": [
            {
              "query": {
                "bool": {
                  "must": [
                    {
                      "query": {
                        "query_string": {
                          "analyze_wildcard": true,
                          "query": "*"
                        }
                      }
                    },
                    {
                      "query": {
                        "query_string": {
                          "query": "_type:familysituation",
                          "analyze_wildcard": true
                        }
                      }
                    }
                  ],
                  "must_not": [],
                  "filter": {
                    "bool": {
                      "must": []
                    }
                  }
                }
              }
            }
          ]
        },
        {
          "pattern": "ct_tada_full_text",
          "path": "id",
          "indices": [
            "ct_tada_full_text"
          ],
          "termsEncoding": "long",
          "types": [
            "person"
          ]
        }
      ]
    }
  ]
}
```

It works !
<img width="445" alt="screen shot 2017-01-05 at 13 48 05" src="https://cloud.githubusercontent.com/assets/5486003/21681039/9d8bcfb2-d34d-11e6-970c-720511415419.png">

Hope that helps ;)

**Comment by scampi** [comment]
I think I got the bug but I would need some more information from you to confirm it is what you see.
Can you share the associated saved searches to the dashboards `Test Relation_fs` and `Test Relation_person` ?

**Comment by olidem57** [comment]
Hi,

I'm sorry I totally forgot to answer your last request.

I can't reproduce the bug anymore so I don't know if giving you my saved searches would still be of any help :/ Did you manage to correct it ?

**Comment by scampi** [comment]
@olidem57 we have something under the radar, but that only happens (from some initial testing) if you are filtering on `_type` in the saved searches associated to the dashboards you are joining.

**Comment by scampi** [comment]
we added a message advising users to use aliases in such a case.
