### ISSUE TITLE
Missing Kibi versions on dockerhub for supported version

### ISSUE THREAD

**Issue by toddgardner** [sirensolutions/kibi#67]
### Versions

Kibi: 4.5.4

Operating System: Docker

### Behavior 

I was looking to try the standalone docker 4.5.4 image, but it looks like the only images available are snapshots of 4.6.2-SNAPSHOT and 4.6.3-SNAPSHOT:

https://hub.docker.com/r/sirensolutions/kibi-community-standalone/tags/

**Comment by fabiocorneti** [comment]
Hello Todd,
we are fixing the standalone images for the releases, they should be available again in a couple days.

**Comment by fabiocorneti** [comment]
Hi Todd,
the images are available again; they have been updated to support a few configuration options as environment variables, see https://hub.docker.com/r/sirensolutions/kibi-community-standalone/ .
