### ISSUE TITLE
ES 5.X Support

### ISSUE THREAD

**Issue by ma-jahn** [sirensolutions/kibi#68]
Hi,

i am currently using Kibi 4.6.3 along with ES 2.4.4 and it's working just fine.
But since ES 5.X is available i'm wondering if there are any plans on releasing a Kibi 5.X version?

Thank you!

**Comment by bertol83** [comment]
Kibi 5 will come soon. A first beta should be available in a couple of weeks.

**Comment by ma-jahn** [comment]
Thank you very much for the quick response!
In this case i'll start a new project using kibi 4.6.3 and try to migrate as soon as the first stable release hits daylight ;)

**Comment by swackhamer** [comment]
Any updates on Kibi 5?  Will this siren-join PR be merged with Kibi 5 coming soon?

https://github.com/sirensolutions/siren-join/pull/120

**Comment by jccq** [comment]
Hi Siren Join 5 is a completely rewritten platform, not just a port. The
rewriting was needed as we evolve Siren toward a universal big data
virtualization platform inside/leveraging ES.

For this that pull request while appreciated cannot be a top priority as we
need to roll out ours (currently feature complete for its first release,
just being poilished).

Kibi 5 is being delayed by the fact that we are going to roll out 4.6.4
first which has dashboard/widget/save search level access control, but i
would expect something in the next couple of weeks anyway.

Today we have released 4.6.3-2, with significant improvements (announcement
to come) so may you enjoy that in the meanwhile :)

best

**Comment by jdeplato** [comment]
Comment for tracking, we are holding off Kibi implementation until ES 5.x support.
Thanks for the efforts!

**Comment by jccq** [comment]
Comment noted! thanks for your patience.


*Giovanni Tummarello*   Siren Solutions - CEO
M +353 87 1272938 |
giovanni@siren.solutions | http://siren.solutions/
Unit 13 GTC, Mervue Park, Galway, Ireland
<http://www.twitter.com/jccq?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<http://youtube.com/c/SirenSolutionsChannel?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/in/giovannitummarello?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by wirecutter313** [comment]
I would love to see this work with ES 5. Anything we can do to help?

**Comment by jccq** [comment]
Hi, thanks for proposing,
 works are in progress, with our core demo running, we need to polish rough
edges and we'll release a beta.

[image: Inline image 1]

*Giovanni Tummarello*   Siren Solutions - CEO
M +353 87 1272938 |
giovanni@siren.solutions | http://siren.solutions/
Unit 13 GTC, Mervue Park, Galway, Ireland
<http://www.twitter.com/jccq?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<http://youtube.com/c/SirenSolutionsChannel?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/in/giovannitummarello?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by sacx** [comment]
Do you have any release date of the beta?

**Comment by jccq** [comment]
Please sign up to the announcement mailing list, last week we have release
4.6.4 now we're focused on 5.2. first beta should be out in a 2-3 week.

thanks

*Giovanni Tummarello*   Siren Solutions - CEO
M +353 87 1272938 |
giovanni@siren.solutions | http://siren.solutions/
Unit 13 GTC, Mervue Park, Galway, Ireland
<http://www.twitter.com/jccq?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<http://youtube.com/c/SirenSolutionsChannel?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/in/giovannitummarello?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by benpolzin** [comment]
Hi Gio,

Are you able to commit to a specific date? It seems 2-3 weeks has been the timeline since January.

- 9/1 - [Q4 2016](https://groups.google.com/a/siren.solutions/d/msg/kibi-users/rz6LUklJRR8/dAKKmWEzDgAJ)
- 12/5 - [beta in January](https://groups.google.com/a/siren.solutions/d/msg/kibi-users/rz6LUklJRR8/UEPKCxqRDAAJ)
- 1/15 - [next few weeks](https://groups.google.com/a/siren.solutions/d/msg/kibi-users/rz6LUklJRR8/s_-l0HWqFQAJ)
- 1/23 - [couple of weeks](https://github.com/sirensolutions/kibi/issues/68#issuecomment-274427432)
- 2/15 - [couple of weeks](https://github.com/sirensolutions/kibi/issues/68#issuecomment-280174987)
- 3/26 - [2-3 weeks](https://github.com/sirensolutions/kibi/issues/68#issuecomment-289313283)

Can you also comment further on ES version compatibility? For folks wanting to run this next Kibi release as soon as possible is the current ES 5.2.2 a safe bet? Thanks!

**Comment by jccq** [comment]
Hi Ben

hard to argue with that, please bear with us as we grow
Reason for the delayed have been us prioritizing the needs of production
Kibi EE customers and Jumpstart Support customers (see our release
announcement today, or anyway download kibi 4.6.4 with major features like
"dashboard object level access control" ) , and these customers are not in
a hurry for  5.x yet.  the good thing is all the improvements we have done
on the 4.x are inherited/pop up in 5.. so nothing lost there, just
prioritizing.

Yes ES 5.2.2 is what we're working on. (first version will be min Kibi
5.2.2 ) about time just hold "a couple of weeks" :), with 4.6.2  it should
be the right time.

Gio

*Giovanni Tummarello*   Siren Solutions - CEO
M +353 87 1272938 |
giovanni@siren.solutions | http://siren.solutions/
Unit 13 GTC, Mervue Park, Galway, Ireland
<http://www.twitter.com/jccq?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<http://youtube.com/c/SirenSolutionsChannel?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/in/giovannitummarello?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by scampi** [comment]
kibi 5.2.2 beta has been released https://github.com/sirensolutions/kibi/releases/tag/tag-5.2.2-beta-1
