### ISSUE TITLE
How can i use solr instead of elasticsearch?

### ISSUE THREAD

**Issue by tirumalavasu** [sirensolutions/kibi#69]
### Versions

Kibi: 4.6.3

Operating System:
Ubuntu 16.04

#### Expected:
Solr instead of elasticsearch

How can i use apache solr instead of elasticsearch?

**Comment by jccq** [comment]
It's not off our radar.  If this request solves an important business need
pls contact us at info@siren.solutions

**Comment by tirumalavasu** [comment]
Thanks for the reply. @jccq
