### ISSUE TITLE
Tabbed dashboards to be proposed in Kibana?

### ISSUE THREAD

**Issue by acs** [sirensolutions/kibi#7]
Hi guys!

First of all, congratulations for your great work extending Kibana to create KIbi.

The tabbed dashboards navigation is pretty cool. Do you plan to propose it as a PR to Kibana project?

Sorry if this is not the right place for this kind of discussion.

Cheers

**Comment by fabiocorneti** [comment]
Hi @acs, thanks for your kind words. After our 0.2 version will be out, we look forward to get the codebase in sync with Kibana 4.2/master, then try to migrate as much features as possible to plugins; after that, we should be able to propose PRs for changes that may be useful upstream.

**Comment by acs** [comment]
Hi @fabiocorneti, really cool plans. We are now in Bitergia approaching [Kibana](http://blog.bitergia.com/2015/10/19/testing-kibana-openstack-code-contributions-dashboard/) and analyzing features we need like the tabbed dashboards, or [labeling metrics](https://github.com/elastic/kibana/issues/4065) and trying to find the best strategy.

We are following carefully the plugins architecture to use it as the extending default approach, as you. And trying also to collaborate upstream for things like metric labeling. 

Maybe we can use email to continue with this conversation. Mine is: acs@bitergia.com.

Thanks!
