### ISSUE TITLE
HTML code for embedding a dashboard includes all dashboards

### ISSUE THREAD

**Issue by brtptrs** [sirensolutions/kibi#71]
### Versions

Kibi: 4.6.3-2

Operating System: Ubuntu 16:04

### Behavior 
"Embed this dashboard"

#### Expected:
One of many dashboards is included in the html code generated by kibi

#### Actual:
Data from more than one dashboards are included in the html code. At the moment we can't identify a pattern to identify which dashboards are included.

### Steps to reproduce the problem
Create more than one dashboard. Click on "share" to create html code to embed in a web page.

**Comment by scampi** [comment]
Can you try with 4.6.4 ? Tested just now and this works. Maybe can you share the URL you copied/pasted ?

**Comment by szydan** [comment]
Closing due to lack of feedback
