### ISSUE TITLE
Relational column based on indexes relations

### ISSUE THREAD

**Issue by gsmetal** [sirensolutions/kibi#74]
Hello! Is there any way to add column to visualization table which will represent field from another index? I only found relation column based on external queries.

I have 2 indexes with projects and time-based events with project-uuid field. I configured relation between indexes and want to show project name in Events visualization table without need of indexing it into events index.

**Comment by jccq** [comment]
Hi there. There are multiple solutions to this we're pondering. 

Could you please rate how important this is for your use case:

* just show
* sort on that field
* export the CSV with that too 
* clicking on the value and going to a connected dashboard with a filter on that.

sure they're all nice to have :) but  we're pondering if to roll out a solution that would address some of this (frontend solution) or do it later when the backend supports it.

**Comment by gsmetal** [comment]
Thanks for quick response!

First of all it's show. And maybe export to CSV. Because I didn't find tools that can combine related data from different indexes and show it together.

Other two cases can be workarounded somehow so they are less important I think.

**Comment by jccq** [comment]
Ok noted, its a highly sought after things we'll roll out in some future version
