### ISSUE TITLE
Kibi 5.2.2 Install Error

### ISSUE THREAD

**Issue by jdeplato** [sirensolutions/kibi#75]
**Kibi version**: 5.2.2

**Elasticsearch version**: 5.2.0

**Server OS version**: Ubuntu 16.04.2 LTS

**Browser version**:

**Browser OS version**:

**Original install method (e.g. download page, from source, etc.)**: git clone, npm install

**Description of the problem including expected versus actual behavior**:

3322 verbose stack Error: java@0.7.2 install: `node-gyp rebuild`
3322 verbose stack Exit status 1
3322 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
3322 verbose stack     at emitTwo (events.js:106:13)
3322 verbose stack     at EventEmitter.emit (events.js:194:7)
3322 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
3322 verbose stack     at emitTwo (events.js:106:13)
3322 verbose stack     at ChildProcess.emit (events.js:194:7)
3322 verbose stack     at maybeClose (internal/child_process.js:899:16)
3322 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
3323 verbose pkgid java@0.7.2
3324 verbose cwd /opt/kibi
3325 error Linux 4.4.0-31-generic
3326 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
3327 error node v7.9.0
3328 error npm  v4.2.0
3329 error code ELIFECYCLE
3330 error errno 1
3331 error java@0.7.2 install: `node-gyp rebuild`
3331 error Exit status 1
3332 error Failed at the java@0.7.2 install script 'node-gyp rebuild'.
3332 error Make sure you have the latest version of node.js and npm installed.
3332 error If you do, this is most likely a problem with the java package,
3332 error not with npm itself.
3332 error Tell the author that this fails on your system:
3332 error     node-gyp rebuild
3332 error You can get information on how to open an issue for this project with:
3332 error     npm bugs java
3332 error Or if that isn't available, you can get their info via:
3332 error     npm owner ls java
3332 error There is likely additional logging output above.
3333 verbose exit [ 1, true ]
                                   
**Steps to reproduce**:
 1. clone git
 2. npm install
 3. error

**Errors in browser console (if relevant)**:

**Provide logs and/or server output (if relevant)**:

**Describe the feature**:

**Comment by lsavio** [comment]
Dear @jdeplato, 
we are trying to reproduce your issue, we will update you as soon as possibile.

Best reguards,
Luigi

**Comment by jdeplato** [comment]
Thanks Luigi!

It may be me - I don't know. It would not install on one of our Ubuntu web servers, so I spun up a clean Ubuntu server, ran into dependency hell, and after I was able to install everything ran into this error.

**Comment by Bonizzi** [comment]
Dear @jdeplato do you have npm updated?

Best regards,
Michela

**Comment by ogubchenko** [comment]
Can you try:
```
sudo apt-get update
sudo apt-get install build-essential
```
and after that re-install

**Comment by jdeplato** [comment]
Hey all.

I did the following:
Rebuilt Ubuntu
apt install build essential
apt install java (open jdk8)

Downloaded Kibi

Got a JAVA_HOME error

set JAVA_HOME in /etc/environment

Started Kibi

All good!!

So there must have been some dependency issue on the other host I was using.

Thanks for the help.

Best, 

Joe

**Comment by lsavio** [comment]
ok, good. If you have any other issues, feel free to ask for help.
thanks
Luigi
