### ISSUE TITLE
Click handler - support to pass search criteria when redirected to dashboard

### ISSUE THREAD

**Issue by aslng** [sirensolutions/kibi#77]
**Kibi version**: 4.6.4

**Elasticsearch version**: 2.4.4

**Server OS version**: ubuntu 14.04

**Browser version**: Chrome 58.0.3029.81

**Browser OS version**: MACOS 10.12.4

**Original install method (e.g. download page, from source, etc.)**: download page

**Description of the problem including expected versus actual behavior**: This is a feature request to allow a search criteria (e.g. pid:1234) being passed and search in the dashboard when the click handler redirects to a dashboard.

**Steps to reproduce**:
 
 

**Errors in browser console (if relevant)**:

**Provide logs and/or server output (if relevant)**:

**Describe the feature**:
In creating a Visualize ==> select "click hander" 
set column: pid; On click I want to: Select the document, Redirect to dashboard: my-dashboard

The feature requests are to allow specifying a search criteria like "pid:@doc[_source][pid]@"

Later when the click-handler is click, it will jump to my-dashboard and filter with the search "pid:1234" where 1234 is the actual value in the record.

**Comment by jccq** [comment]
this is important indeed, we're working on the design to cover several use cases also outside the click on the table
