### ISSUE TITLE
Save button in management is disabled

### ISSUE THREAD

**Issue by mickaelleclercq** [sirensolutions/kibi#80]
**Kibi version**: 5.2.2-beta-1

**Elasticsearch version**: 5.4.0

**Server OS version**: CentOS Linux 7

**Browser version**: Chromium 58.0.3029.110

**Browser OS version**: Ubuntu 16.04 (64-bit)

**Original install method (e.g. download page, from source, etc.)**: download page

**Description of the problem including expected versus actual behavior**:
In Management, the Save button (upper right of the screen) is deactivated (grey) in "Relations", "Datasources", "Queries", "Query Templates" and "Dashboard Groups". I tested many ways to create relations or dashboards groups, the button stays grey.

In the previous version of Kibi the saving was done automatically in "Relations". 
Any idea to get the "save" button working?

Thank you

**Comment by scampi** [comment]
Thanks for the feedback. The latest kibi on master has the fix, the next beta release will have it.

**Comment by scampi** [comment]
this is the commit: https://github.com/sirensolutions/kibi/commit/1b67c6e02c4a80333db902d021686c377a39e2ad
