### ISSUE TITLE
Kibi version

### ISSUE THREAD

**Issue by hello4usharath** [sirensolutions/kibi#89]
Hi ,

We are using elasticsearch 5.5.1. what is kibi version and will support elastic 5.5.1.

Thanks
Sharath

**Comment by ebdavison** [comment]
Bump. When will 5.5.1 be supported?

**Comment by szydan** [comment]
According to compatibility table here 
https://support.siren.solutions/support/solutions/articles/17000058666-platform-5-4-3-1

Kibi 5.4.3-1 supports Elasticsearch versions 5.4.1, 5.4.3 and 5.5.2
It was not yet fully tested with 5.5.1 but it should work fine.
Please give it a try

**Comment by szydan** [comment]
There is an issue in 5.4.3-1 about creating mappings when using Elasticsearch 5.5.x
The workaround described here 
https://github.com/sirensolutions/kibi/issues/91
It will be fully addressed in 5.4.3-2 release
