### ISSUE TITLE
Elasticsearch 2

### ISSUE THREAD

**Issue by pavel-arapov** [sirensolutions/kibi#9]
Hello,

Just want to know than you plan to upgrade the core to use Elasticsearch 2 (it might be merging Kibana 4.3 in Kibi, I suppose), currently I see next message

> Kibana: This version of Kibana requires Elasticsearch ^1.4.4 on all nodes. I found the following  incompatible nodes in your cluster: 
> 
> Elasticsearch v2.1.0 @ localhost/127.0.0.1:9200 (127.0.0.1)

It is completely blocked me to test your solution :-( 

Looking forward to see a new version,
Pavel

**Comment by jccq** [comment]
Hi Pavel

believe me we're hard at work, join tests are passing, we're merging with
Kibana 4.4 actually ;-) ETA for a full release by Elasticon (maybe earlier
though..)

apologies for the delays, next versions will be quicker to follow for us
than the full 1.x to 2.x jump

On Tue, Jan 19, 2016 at 10:56 AM, Pavel Arapov notifications@github.com
wrote:

> Hello,
> 
> Just want to know than you plan to upgrade the core to use Elasticsearch 2
> (it might be merging Kibana 4.3 in Kibi, I suppose), currently I see next
> message
> 
> Kibana: This version of Kibana requires Elasticsearch ^1.4.4 on all nodes.
> I found the following incompatible nodes in your cluster:
> 
> Elasticsearch v2.1.0 @ localhost/127.0.0.1:9200 (127.0.0.1)
> 
> It is completely blocked me to test your solution :-(
> 
> Looking forward to see a new version,
> Pavel
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sirensolutions/kibi/issues/9.

## 

Giovanni Tummarello
CEO - SIREn Solutions

**Comment by pavel-arapov** [comment]
Hi Giovanni,

thank you for your reply. I am really impressed by the demo and documentation, looking forward to test new version, I hope before Elasticon! :-)

**Comment by jccq** [comment]
thanks :)

latest news from the team is that we'll likely have an alpha/beta next
week. lets see

On Tue, Jan 19, 2016 at 1:31 PM, Pavel Arapov notifications@github.com
wrote:

> Hi Giovanni,
> 
> thank you for your reply. I am really impressed by the demo and
> documentation, looking forward to test new version, I hope before
> Elasticon! :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sirensolutions/kibi/issues/9#issuecomment-172853777.

## 

Giovanni Tummarello
CEO - SIREn Solutions

**Comment by gytisgreitai** [comment]
Any chance of getting that beta? Thanks!

**Comment by jccq** [comment]
Hi, yes the beta will be available starting tomorrow to beta testing
partners

In the (near) future we will have a way on the website to register,  for
now please write me giovanni@siren.solutions

In any case the full version will be out by next week the latest.
Gio

On Sun, Jan 31, 2016 at 3:01 PM, Gytis notifications@github.com wrote:

> Any chance of getting that beta? Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sirensolutions/kibi/issues/9#issuecomment-177516829.

## 

Giovanni Tummarello
CEO - SIREn Solutions

**Comment by yehosef** [comment]
+1

**Comment by scampi** [comment]
Please see https://github.com/sirensolutions/siren-join/releases/tag/2.1.2
