### ISSUE TITLE
kibi_multi_chart_vis

### ISSUE THREAD

**Issue by xycloud** [sirensolutions/kibi#90]
will kibi_multi_chart_vis be open sourced ?

**Comment by jccq** [comment]
Not in the plans now but it is available in kibi also in the free licence
one

**Comment by xycloud** [comment]
where can I get the free licence for using kibi_multi_chart_vis

**Comment by jccq** [comment]
the kibi multi chart is part of the siren platform distribution for which
there exists a free licence. http://support.siren.solutions
 Multichart doesnt work on Kibana
