### ISSUE TITLE
Unable to create index

### ISSUE THREAD

**Issue by ebdavison** [sirensolutions/kibi#91]
**Kibi version**: 5.4.3 (downloaded master branch from git)

**Elasticsearch version**: 5.5.1

**Server OS version**: centos 7

**Browser version**: firefox 55

**Browser OS version**: windows

**Original install method (e.g. download page, from source, etc.)**: from github

**Description of the problem including expected versus actual behavior**: 
need to create default index and receiving error when trying.

**Steps to reproduce**:
 1. start kibi
 2. browse to kibi
 3. then asked to create default index
4. attempt to create index "api-*" with "@timestamp" as the field.

**Errors in browser console (if relevant)**:
Error: Request to Elasticsearch failed: "[Not Found] [type_missing_exception] type[[index-pattern]] missing, with { index_uuid=\"_na_\" & index=\"_all\" }"
KbnError@http://10.0.10.61:5606/bundles/commons.bundle.js?v=8467:90:20620
RequestFailure@http://10.0.10.61:5606/bundles/commons.bundle.js?v=8467:90:21369
exports.default/</<@http://10.0.10.61:5606/bundles/kibana.bundle.js?v=8467:26:18303
processQueue@http://10.0.10.61:5606/bundles/commons.bundle.js?v=8467:38:24400
scheduleProcessQueue/<@http://10.0.10.61:5606/bundles/commons.bundle.js?v=8467:38:24667
$eval@http://10.0.10.61:5606/bundles/commons.bundle.js?v=8467:39:5594
$digest@http://10.0.10.61:5606/bundles/commons.bundle.js?v=8467:39:3404
$apply@http://10.0.10.61:5606/bundles/commons.bundle.js?v=8467:39:6013
done@http://10.0.10.61:5606/bundles/commons.bundle.js?v=8467:37:25737
completeRequest@http://10.0.10.61:5606/bundles/commons.bundle.js?v=8467:37:29423
createHttpBackend/</xhr.onload@http://10.0.10.61:5606/bundles/commons.bundle.js?v=8467:37:30355

**Provide logs and/or server output (if relevant)**:

**Comment by szydan** [comment]
Hi @ebdavison
Thanks for the report 

This was already fixed in branch-5.4.3
https://github.com/sirensolutions/kibi/tree/branch-5.4.3
in this commit
https://github.com/sirensolutions/kibi/commit/aa30ff0647101610d62ea0c1a3a54da29506f948

Please try to run Kibi from this branch 
The fix will be included into 5.4.3-2 release which should be out in a week

**Comment by ebdavison** [comment]
Thank you; that does work if I use branch-5.4.3.
