### ISSUE TITLE
Discover: [security_exception] action [indices:siren/mplan] is unauthorized for user [elastic]

### ISSUE THREAD

**Issue by HandsomeWins** [sirensolutions/kibi#93]
**Kibi version**: 5.4.3-1

**Elasticsearch version**: 5.5.2

**Server OS version**: SLES11 SP4 x64

**Browser version**: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Browser OS version**: Chrome

**Original install method (e.g. download page, from source, etc.)**: Siren support section download page.

**Description of the problem including expected versus actual behavior**: Trying to view data from one of my indexes in the discover tab results in security warning messages about how elastic (the superuser account when you're using X-Pack) doesn ot have permission to access a siren-related index.

"Discover: [security_exception] action [indices:siren/mplan] is unauthorized for user [elastic]"

I don't see any information in the user guide related to this except for information about configuring Search Guard to allow access to this index. I'm not using Search Guard though. 

**Steps to reproduce**:
 1. Install Elasticsearch 5.5.2, install X-Pack, install Vanguard
 2. Run Kibi, define an index pattern for the index
 3. Try to view data from the index in the Discover tab

**Errors in browser console (if relevant)**:
Discover: [security_exception] action [indices:siren/mplan] is unauthorized for user [elastic]

**Provide logs and/or server output (if relevant)**:
The logs don't show anything relevant related to this message, even with the --verbose flag passed to Kibi.

**Comment by bertol83** [comment]
A full compatibility with xpack will be available with the next siren platform release (available next week). At the moment we assure our stack is compatible and working with searchguard for access control, and alerting an monitoring are provided by our component sentinl (monitoring, access control, alerting, graph browser should replace xpack)

**Comment by HandsomeWins** [comment]
Waiting patiently for 5.4.3-2! :)

**Comment by HandsomeWins** [comment]
Hello, I see a bump to version 5.5.2 SNAPSHOT on the Kibi Github page, can you please point me in the direction of how to utilize this new version? Thanks!

**Comment by bertol83** [comment]
If you want 5.4.3-2 is available on support.siren.io

**Comment by szydan** [comment]
Hi @HandsomeWins 
Yes master was synced yesterday and is currently at 5.5.2 however it is not ready yet for the official release 
You can build yourself a 5.5.2-SNAPSHOT version from sources but it might still be unstable
Note that the latest official release 5.4.3-2
https://support.siren.solutions/support/solutions/articles/17000061291-platform-5-4-3-2
will work fine with elastic 5.4.3, 5.5.2 and 5.5.3

**Comment by HandsomeWins** [comment]
Issue went away with the newer versions of Siren as promised. Thanks!
