### ISSUE TITLE
how can we make discover page pageable

### ISSUE THREAD

**Issue by xycloud** [sirensolutions/kibi#96]
discover page use docTable directive, kibi modify the source code to make it pageable。seems this config is not enabled in discover page, how can we make it?

**Comment by xycloud** [comment]
any progress?

**Comment by jccq** [comment]
watch for Siren 10 beta @colmose pls add this one if its not already.

**Comment by xycloud** [comment]
awesome, would you mind to tell when new kibi version will be released
