### ISSUE TITLE
elasticsearch 6 support

### ISSUE THREAD

**Issue by ivgenys** [sirensolutions/kibi#98]
When can we expect elasticsearch 6 support for kibi?

**Comment by jccq** [comment]
Hi the next releases (siren 10) focuses on cluster scalable joins when ES
is in use but also JDBC direct connectivity (!). This is Feb.

Es 6.x comes after that so likely from April on

Best



Elasticsearch 6 will come later to that so sometimes past

We will then look into supporting

**Comment by jccq** [comment]
Elasticsearch 6.x support is schedule in the next version 10.1, ETA sometime June.

**Comment by groverjatin17** [comment]
Hi, Does Siren Platform work for Elasticsearch 6.x.
[Here](https://support.siren.io/support/solutions/articles/17000075025-platform-10-0-2) they have mentioned that latest version Siren 10.2 that is released in July stretches till 5.6.10  but nowhere have they mentioned about 6.x.
