### ISSUE TITLE
Docker using different auth credentials

### ISSUE THREAD

**Issue by mjp0** [sirensolutions/kibi#99]
I'm trying to get Kibi 5.4.3-2 Docker (sirensolutions/siren-platform) working but none of the credentials (kibiadmin etc) in the documentation works. I also tried siren-platform-demo-data and it seems to suffer from the same problem.

Please update the docs.

**Comment by szydan** [comment]
Hi @0fork I've tried with 
docker run -d -p 5606:5606 -p 9220:9220 sirensolutions/siren-platform:latest
It seems to be working for me 
One possibility is that the elasticsearch "inside" your docker might be unable to start and it keeps restarting 
You can check  this by doing 
```
docker exec -it YOUR_DOCKER_ID bash
tail -f  /opt/kibi/elasticsearch/elasticsearch.stdout
```
If you see that elasticsearch keeps restarting
you might need to set the **vm.max_map_count** value on the host machine
The instructions how to set it are here 
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/docker.html#docker-cli-run-prod-mode

**Comment by mjp0** [comment]
@szydan That was it! Thank you!

When somebody from the dev team has "few mins" to spare, it might be helpful to add some sort of error message to the login screen if elastic is down. I'm running Ubuntu 16.04 and it didn't even have that vm.max_map_count setting for some reason so I'm guessing that plenty others have and will run into this issue with elastic as well unfortunately.

**Comment by szydan** [comment]
@0fork Thanks for reporting this
Good to hear it solved the issue for you 
I've opened an internal issue about it, we will improve it for the next release
